### ISSUE TITLE
Could not pass event PlaceBlockEvent: null

### ISSUE THREAD

**Issue by xMrEnderman** [EngineHub/WorldGuard#1571]
**Versions**
WorldEdit version: FAWE build 199
WorldGuard version:  v7.0.2
Platform version: paper build 260

**Describe the bug**
I have an error in my console:
[09:13:12] [Server thread/ERROR]: Could not pass event UseBlockEvent to WorldGuard v7.0.2-SNAPSHOT;bf2593e
java.lang.NullPointerException: null
[09:13:12] [Server thread/ERROR]: Could not pass event BreakBlockEvent to WorldGuard v7.0.2-SNAPSHOT;bf2593e
java.lang.NullPointerException: null
[09:13:12] [Server thread/ERROR]: Could not pass event PlaceBlockEvent to WorldGuard v7.0.2-SNAPSHOT;bf2593e
java.lang.NullPointerException: null

**Expected behavior**
Add FAWE support do WorldGuard? I don't know.

**Comment by xMrEnderman** [comment]
[10:48:02] [Server thread/ERROR]: Could not pass event UseBlockEvent to WorldGuard v7.0.2-SNAPSHOT;bf2593e
java.lang.NullPointerException: null
	at com.sk89q.worldedit.bukkit.WorldEditPlugin.getCachedPlayer(WorldEditPlugin.java:581) ~[?:?]
	at com.sk89q.worldedit.bukkit.BukkitPlayer.getExistingMap(BukkitPlayer.java:93) ~[?:?]
	at com.sk89q.worldedit.bukkit.BukkitPlayer.<init>(BukkitPlayer.java:79) ~[?:?]
	at com.sk89q.worldguard.bukkit.BukkitPlayer.<init>(BukkitPlayer.java:43) ~[?:?]
	at com.sk89q.worldguard.bukkit.BukkitPlayer.<init>(BukkitPlayer.java:39) ~[?:?]
	at com.sk89q.worldguard.bukkit.BukkitOfflinePlayer.<init>(BukkitOfflinePlayer.java:42) ~[?:?]
	at com.sk89q.worldguard.bukkit.WorldGuardPlugin.wrapOfflinePlayer(WorldGuardPlugin.java:452) ~[?:?]
	at com.sk89q.worldguard.bukkit.listener.AbstractListener.createRegionAssociable(AbstractListener.java:126) ~[?:?]
	at com.sk89q.worldguard.bukkit.listener.RegionProtectionListener.onUseBlock(RegionProtectionListener.java:249) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor269.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-260]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-260]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-260]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-260]
	at com.sk89q.worldguard.bukkit.util.Events.fireAndTestCancel(Events.java:60) ~[?:?]
	at com.sk89q.worldguard.bukkit.listener.debounce.legacy.AbstractEventDebounce.debounce(AbstractEventDebounce.java:56) ~[?:?]
	at com.sk89q.worldguard.bukkit.listener.debounce.legacy.BlockEntityEventDebounce.debounce(BlockEntityEventDebounce.java:36) ~[?:?]
	at com.sk89q.worldguard.bukkit.listener.EventAbstractionListener.onEntityInteract(EventAbstractionListener.java:499) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor321.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-260]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-260]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-260]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-260]
	at net.minecraft.server.v1_15_R1.BlockRedstoneOre.stepOn(BlockRedstoneOre.java:43) ~[patched_1.15.2.jar:git-Paper-260]
	at net.minecraft.server.v1_15_R1.Entity.move(Entity.java:686) ~[patched_1.15.2.jar:git-Paper-260]
	at net.minecraft.server.v1_15_R1.EntityLiving.e(EntityLiving.java:2270) ~[patched_1.15.2.jar:git-Paper-260]
	at net.minecraft.server.v1_15_R1.EntityLiving.movementTick(EntityLiving.java:2637) ~[patched_1.15.2.jar:git-Paper-260]
	at net.minecraft.server.v1_15_R1.EntityInsentient.movementTick(EntityInsentient.java:525) ~[patched_1.15.2.jar:git-Paper-260]
	at net.minecraft.server.v1_15_R1.EntityAgeable.movementTick(EntityAgeable.java:171) ~[patched_1.15.2.jar:git-Paper-260]
	at net.minecraft.server.v1_15_R1.EntityAnimal.movementTick(EntityAnimal.java:28) ~[patched_1.15.2.jar:git-Paper-260]
	at net.minecraft.server.v1_15_R1.EntityLiving.tick(EntityLiving.java:2396) ~[patched_1.15.2.jar:git-Paper-260]
	at net.minecraft.server.v1_15_R1.EntityInsentient.tick(EntityInsentient.java:288) ~[patched_1.15.2.jar:git-Paper-260]
	at net.minecraft.server.v1_15_R1.EntityCat.tick(EntityCat.java:211) ~[patched_1.15.2.jar:git-Paper-260]
	at net.minecraft.server.v1_15_R1.WorldServer.entityJoinedWorld(WorldServer.java:803) ~[patched_1.15.2.jar:git-Paper-260]
	at net.minecraft.server.v1_15_R1.World.a(World.java:874) ~[patched_1.15.2.jar:git-Paper-260]
	at net.minecraft.server.v1_15_R1.WorldServer.doTick(WorldServer.java:528) ~[patched_1.15.2.jar:git-Paper-260]
	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1315) ~[patched_1.15.2.jar:git-Paper-260]
	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-260]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1169) ~[patched_1.15.2.jar:git-Paper-260]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:958) ~[patched_1.15.2.jar:git-Paper-260]
	at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by JOO200** [comment]
WorldEdit forks are not supported. Try to use the default worldedit version (7.1.0).
