### ISSUE TITLE
WorldGuard not starting.

### ISSUE THREAD

**Issue by benrobson** [EngineHub/WorldGuard#1607]
**Versions**

WorldEdit version: 7.1.0

WorldGuard version:
v7.0.3;5407315
Platform version:
1.16.1

**Describe the bug**

```
[19:21:47 INFO]: [WorldGuard] Enabling WorldGuard v7.0.3;5407315
[19:21:47 INFO]: [WorldGuard] (world) TNT ignition is PERMITTED.
[19:21:47 INFO]: [WorldGuard] (world) Lighters are PERMITTED.
[19:21:47 INFO]: [WorldGuard] (world) Lava fire is PERMITTED.
[19:21:47 INFO]: [WorldGuard] (world) Fire spread is UNRESTRICTED.
[19:21:47 INFO]: [WorldGuard] Loaded configuration for world 'world'
[19:21:47 INFO]: [WorldGuard] Loading region data...
[19:21:47 ERROR]: Error occurred while enabling WorldGuard v7.0.3;5407315 (Is it up to date?)
java.lang.NoSuchMethodError: com.sk89q.minecraft.util.commands.Injector.getProviderOrNull(Ljava/lang/Class;)Ljavax/inject/Provider;
        at com.sk89q.minecraft.util.commands.CommandsManager.registerMethods0(CommandsManager.java:198) ~[?:?]
        at com.sk89q.minecraft.util.commands.CommandsManager.registerMethods(CommandsManager.java:147) ~[?:?]
        at com.sk89q.bukkit.util.CommandsManagerRegistration.register(CommandsManagerRegistration.java:61) ~[?:?]
        at com.sk89q.bukkit.util.CommandsManagerRegistration.register(CommandsManagerRegistration.java:57) ~[?:?]
        at com.sk89q.worldguard.bukkit.WorldGuardPlugin.onEnable(WorldGuardPlugin.java:155) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.1.jar:git-Paper-90]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.1.jar:git-Paper-90]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.1.jar:git-Paper-90]
        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin(CraftServer.java:500) ~[patched_1.16.1.jar:git-Paper-90]
        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugins(CraftServer.java:414) ~[patched_1.16.1.jar:git-Paper-90]
        at net.minecraft.server.v1_16_R1.MinecraftServer.loadWorld(MinecraftServer.java:471) ~[patched_1.16.1.jar:git-Paper-90]
        at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:241) ~[patched_1.16.1.jar:git-Paper-90]
        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:940) ~[patched_1.16.1.jar:git-Paper-90]
        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-90]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
[19:21:47 INFO]: [WorldGuard] Disabling WorldGuard v7.0.3;5407315
[19:21:47 INFO]: [WorldGuard] Shutting down executor and cancelling any pending tasks...
```

**To Reproduce**

Update the server 1.16.1.

**Expected behavior**

Should be operational and loading.

**Comment by me4502** [comment]
Join the Discord and provide your full log, this doesn't seem to be a bug
