### ISSUE TITLE
Support async Vault requests (LuckPerms support)

### ISSUE THREAD

**Issue by smartmadio** [EngineHub/WorldGuard#1632]
```
[09:44:25] [Server thread/ERROR]: Could not pass event DamageEntityEvent to WorldGuard v7.0.4-beta1;bc551da
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.RuntimeException: The operation to load user data for '46806d8f-58ed-3397-ab49-1cf6ae64daf4' was cancelled by LuckPerms. This is NOT a bug. 
The lookup request was made on the main server thread. It is not safe to execute a request to 
load data for offline players from the database in this context. 
If you are a plugin author, please consider making your request asynchronously. 
Alternatively, server admins can disable this catch by setting 'vault-unsafe-lookups' to true 
in the LP config, but should consider the consequences (lag) before doing so.
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2217) ~[patched_1.16.1.jar:git-Paper-136]
	at com.google.common.cache.LocalCache.get(LocalCache.java:4154) ~[patched_1.16.1.jar:git-Paper-136]
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158) ~[patched_1.16.1.jar:git-Paper-136]
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147) ~[patched_1.16.1.jar:git-Paper-136]
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5153) ~[patched_1.16.1.jar:git-Paper-136]
	at com.sk89q.worldguard.session.AbstractSessionManager.hasBypass(AbstractSessionManager.java:138) ~[?:?]
	at com.sk89q.worldguard.bukkit.session.BukkitSessionManager.hasBypass(BukkitSessionManager.java:81) ~[?:?]
	at com.sk89q.worldguard.bukkit.listener.RegionProtectionListener.isWhitelisted(RegionProtectionListener.java:145) ~[?:?]
	at com.sk89q.worldguard.bukkit.listener.RegionProtectionListener.onDamageEntity(RegionProtectionListener.java:449) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor201.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.1.jar:git-Paper-136]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.1.jar:git-Paper-136]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.1.jar:git-Paper-136]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.1.jar:git-Paper-136]
	at com.sk89q.worldguard.bukkit.util.Events.fireToCancel(Events.java:74) ~[?:?]
	at com.sk89q.worldguard.bukkit.listener.EventAbstractionListener.onEntityDamage(EventAbstractionListener.java:849) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor229.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.1.jar:git-Paper-136]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.1.jar:git-Paper-136]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.1.jar:git-Paper-136]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.1.jar:git-Paper-136]
	at org.bukkit.craftbukkit.v1_16_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:247) ~[patched_1.16.1.jar:git-Paper-136]
	at org.bukkit.craftbukkit.v1_16_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1035) ~[patched_1.16.1.jar:git-Paper-136]
	at org.bukkit.craftbukkit.v1_16_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:922) ~[patched_1.16.1.jar:git-Paper-136]
	at org.bukkit.craftbukkit.v1_16_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:878) ~[patched_1.16.1.jar:git-Paper-136]
	at org.bukkit.craftbukkit.v1_16_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1067) ~[patched_1.16.1.jar:git-Paper-136]
	at net.minecraft.server.v1_16_R1.EntityLiving.damageEntity0(EntityLiving.java:1823) ~[patched_1.16.1.jar:git-Paper-136]
	at net.minecraft.server.v1_16_R1.EntityLiving.damageEntity(EntityLiving.java:1159) ~[patched_1.16.1.jar:git-Paper-136]
	at net.minecraft.server.v1_16_R1.EntityMonster.damageEntity(EntityMonster.java:52) ~[patched_1.16.1.jar:git-Paper-136]
	at net.minecraft.server.v1_16_R1.EntityWither.damageEntity(EntityWither.java:474) ~[patched_1.16.1.jar:git-Paper-136]
	at net.minecraft.server.v1_16_R1.EntitySnowball.a(SourceFile:58) ~[patched_1.16.1.jar:git-Paper-136]
	at net.minecraft.server.v1_16_R1.IProjectile.a(IProjectile.java:125) ~[patched_1.16.1.jar:git-Paper-136]
	at net.minecraft.server.v1_16_R1.EntitySnowball.a(SourceFile:63) ~[patched_1.16.1.jar:git-Paper-136]
	at net.minecraft.server.v1_16_R1.EntityProjectile.tick(EntityProjectile.java:53) ~[patched_1.16.1.jar:git-Paper-136]
	at net.minecraft.server.v1_16_R1.WorldServer.entityJoinedWorld(WorldServer.java:833) ~[patched_1.16.1.jar:git-Paper-136]
	at net.minecraft.server.v1_16_R1.World.a(World.java:927) ~[patched_1.16.1.jar:git-Paper-136]
	at net.minecraft.server.v1_16_R1.WorldServer.doTick(WorldServer.java:525) ~[patched_1.16.1.jar:git-Paper-136]
	at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1360) ~[patched_1.16.1.jar:git-Paper-136]
	at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.1.jar:git-Paper-136]
	at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1213) ~[patched_1.16.1.jar:git-Paper-136]
	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1001) ~[patched_1.16.1.jar:git-Paper-136]
	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-136]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
```
This message spams in console and caused a 771MB latest.log.

**Describe the solution you'd like**
- I would like worldguard could support async Vault requests(LuckPerms support).

**Server environment**
- Server version: 1.16.2
- WorldGuard version: v7.0.4-beta1
- Vault version: 1.7.3

**Comment by wizjany** [comment]
dupe
