### ISSUE TITLE
worldguard no commands. says error

### ISSUE THREAD

**Issue by Nukekiller007** [EngineHub/WorldGuard#1633]
[14:43:31] [Server thread/ERROR]: Error occurred while enabling WorldGuard v7.0.4-beta1;bc551da (Is it up to date?)
java.util.concurrent.CompletionException: net.minecraft.server.v1_16_R2.ReportedException: Exception generating new chunk
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273) ~[?:1.8.0_211]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280) ~[?:1.8.0_211]
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:961) ~[?:1.8.0_211]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926) ~[?:1.8.0_211]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) ~[?:1.8.0_211]
	at net.minecraft.server.v1_16_R2.ChunkTaskQueueSorter.b(SourceFile:58) ~[Spigot_Latest.jar:git-Spigot-b5a13e6-927200a]
	at net.minecraft.server.v1_16_R2.ThreadedMailbox.e(SourceFile:94) ~[Spigot_Latest.jar:git-Spigot-b5a13e6-927200a]
	at net.minecraft.server.v1_16_R2.ThreadedMailbox.a(SourceFile:137) ~[Spigot_Latest.jar:git-Spigot-b5a13e6-927200a]
	at net.minecraft.server.v1_16_R2.ThreadedMailbox.run(SourceFile:105) ~[Spigot_Latest.jar:git-Spigot-b5a13e6-927200a]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402) ~[?:1.8.0_211]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_211]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_211]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[?:1.8.0_211]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_211]
Caused by: net.minecraft.server.v1_16_R2.ReportedException: Exception generating new chunk
	at net.minecraft.server.v1_16_R2.PlayerChunkMap.lambda$26(PlayerChunkMap.java:551) ~[Spigot_Latest.jar:git-Spigot-b5a13e6-927200a]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[Spigot_Latest.jar:git-Spigot-b5a13e6-927200a]
	at net.minecraft.server.v1_16_R2.PlayerChunkMap.lambda$24(PlayerChunkMap.java:536) ~[Spigot_Latest.jar:git-Spigot-b5a13e6-927200a]
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952) ~[?:1.8.0_211]
	... 11 more
Caused by: java.lang.UnsupportedOperationException: Custom generator multiworld.worldgen.FlatLandChunkGenerator is missing required method generateChunkData
	at org.bukkit.generator.ChunkGenerator.generateChunkData(ChunkGenerator.java:117) ~[Spigot_Latest.jar:git-Spigot-b5a13e6-927200a]
	at org.bukkit.craftbukkit.v1_16_R2.generator.CustomChunkGenerator.buildBase(CustomChunkGenerator.java:122) ~[Spigot_Latest.jar:git-Spigot-b5a13e6-927200a]
	at net.minecraft.server.v1_16_R2.ChunkStatus.lambda$5(ChunkStatus.java:55) ~[Spigot_Latest.jar:git-Spigot-b5a13e6-927200a]
	at net.minecraft.server.v1_16_R2.ChunkStatus$d.doWork(ChunkStatus.java:233) ~[Spigot_Latest.jar:git-Spigot-b5a13e6-927200a]
	at net.minecraft.server.v1_16_R2.ChunkStatus.a(ChunkStatus.java:190) ~[Spigot_Latest.jar:git-Spigot-b5a13e6-927200a]
	at net.minecraft.server.v1_16_R2.PlayerChunkMap.lambda$26(PlayerChunkMap.java:538) ~[Spigot_Latest.jar:git-Spigot-b5a13e6-927200a]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[Spigot_Latest.jar:git-Spigot-b5a13e6-927200a]
	at net.minecraft.server.v1_16_R2.PlayerChunkMap.lambda$24(PlayerChunkMap.java:536) ~[Spigot_Latest.jar:git-Spigot-b5a13e6-927200a]
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952) ~[?:1.8.0_211]
	... 11 more

**Comment by wizjany** [comment]
`Caused by: java.lang.UnsupportedOperationException: Custom generator multiworld.worldgen.FlatLandChunkGenerator is missing required method generateChunkData`
