### ISSUE TITLE
Disabled on Boot with Paper-457

### ISSUE THREAD

**Issue by lukezon** [EngineHub/WorldGuard#1720]
**Describe the bug**
Plugin disables on server start using latest paper version (1.16.5-Paper-457).

**To Reproduce**
Start the paper server with the plugin installed.

**Expected behavior**
Server doesn't crash.

**Additional context**
`[10:10:42] [Server thread/ERROR]: Error occurred while enabling WorldGuard v7.0.4+f7ff984 (Is it up to date?)
java.lang.AbstractMethodError: java.nio.ByteBuffer.get()B
	at sun.nio.cs.UTF_8$Decoder.decodeBufferLoop(UTF_8.java:328) ~[?:1.8.0_275]
	at sun.nio.cs.UTF_8$Decoder.decodeLoop(UTF_8.java:414) ~[?:1.8.0_275]
	at java.nio.charset.CharsetDecoder.decode(CharsetDecoder.java:579) ~[?:1.8.0_275]
	at java.nio.charset.CharsetDecoder.decode(CharsetDecoder.java:802) ~[?:1.8.0_275]
	at java.nio.charset.Charset.decode(Charset.java:807) ~[?:1.8.0_275]
	at org.sqlite.core.NativeDB.utf8ByteBufferToString(NativeDB.java:507) ~[patched_1.16.5.jar:git-Paper-457]
	at org.sqlite.core.NativeDB.errmsg(NativeDB.java:144) ~[patched_1.16.5.jar:git-Paper-457]
	at org.sqlite.core.DB.newSQLException(DB.java:1024) ~[patched_1.16.5.jar:git-Paper-457]
	at org.sqlite.core.DB.throwex(DB.java:989) ~[patched_1.16.5.jar:git-Paper-457]
	at org.sqlite.core.NativeDB._exec_utf8(Native Method) ~[patched_1.16.5.jar:git-Paper-457]
	at org.sqlite.core.NativeDB._exec(NativeDB.java:94) ~[patched_1.16.5.jar:git-Paper-457]
	at org.sqlite.jdbc3.JDBC3Statement.executeUpdate(JDBC3Statement.java:102) ~[patched_1.16.5.jar:git-Paper-457]
	at com.sk89q.worldguard.util.profile.cache.SQLiteCache.createTable(SQLiteCache.java:108) ~[?:?]
	at com.sk89q.worldguard.util.profile.cache.SQLiteCache.<init>(SQLiteCache.java:72) ~[?:?]
	at com.sk89q.worldguard.WorldGuard.setup(WorldGuard.java:83) ~[?:?]
	at com.sk89q.worldguard.bukkit.WorldGuardPlugin.onEnable(WorldGuardPlugin.java:142) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-457]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.5.jar:git-Paper-457]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.5.jar:git-Paper-457]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.5.jar:git-Paper-457]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.5.jar:git-Paper-457]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:465) ~[patched_1.16.5.jar:git-Paper-457]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:239) ~[patched_1.16.5.jar:git-Paper-457]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:936) ~[patched_1.16.5.jar:git-Paper-457]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:174) ~[patched_1.16.5.jar:git-Paper-457]`

**Comment by wizjany** [comment]
last person who had this had to update their jdk.
basically nothing we can do here, there's an issue between the sqlite provided by the server and your java installation.
