### ISSUE TITLE
Asynchronous notify call java.lang.Throwable: null error sometimes

### ISSUE THREAD

**Issue by andris155** [EngineHub/WorldGuard#1724]
**Versions**

WorldEdit version: FastAsyncWorldEdit version 1.16-592;ac16c9a

WorldGuard version: WorldGuard version 7.0.4+f7ff984

Platform version: This server is running Yatopia version git-Yatopia-ver/1.16.5-21 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

**Describe the bug**

Asynchronous notify call java.lang.Throwable: null error sometimes

**To Reproduce**

I don't know. I find this error on console.

**Expected behavior**

No write this error on console.

**Screenshots**

**Additional context**

```
[19:09:20] [WorldGuard Task Executor - 58/FATAL]: Thread WorldGuard Task Executor - 58 failed thread check for reason: Asynchronous notify call
java.lang.Throwable: null
	at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-21]
	at net.minecraft.server.v1_16_R3.WorldServer.notify(WorldServer.java:2143) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-21]
	at net.minecraft.server.v1_16_R3.TileEntityCommand$1.e(TileEntityCommand.java:34) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-21]
	at net.minecraft.server.v1_16_R3.CommandBlockListenerAbstract.sendMessage(CommandBlockListenerAbstract.java:164) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-21]
	at org.bukkit.craftbukkit.v1_16_R3.command.CraftBlockCommandSender.sendMessage(CraftBlockCommandSender.java:33) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-21]
	at com.sk89q.worldedit.util.formatting.text.adapter.bukkit.LegacyAdapter.sendMessage(LegacyAdapter.java:36) ~[?:?]
	at com.sk89q.worldedit.util.formatting.text.adapter.bukkit.TextAdapter0.sendComponent(TextAdapter.java:138) ~[?:?]
	at com.sk89q.worldedit.util.formatting.text.adapter.bukkit.TextAdapter.sendComponent(TextAdapter.java:82) ~[?:?]
	at com.sk89q.worldedit.util.formatting.text.adapter.bukkit.TextAdapter.sendComponent(TextAdapter.java:70) ~[?:?]
	at com.sk89q.worldedit.bukkit.BukkitCommandSender.print(BukkitCommandSender.java:103) ~[?:?]
	at com.sk89q.worldedit.command.util.AsyncCommandBuilder.runTask(AsyncCommandBuilder.java:145) ~[?:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:111) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-21]
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:58) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-21]
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:75) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-21]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
```

**Comment by wizjany** [comment]
your best bet is probably not to run whatever commands you're trying to run in command blocks. the alternative is we just not try to send command output to commands blocks but WG itself isn't actually aware of command blocks, we just treat it like console.
