### ISSUE TITLE
InvalidPluginException on startup

### ISSUE THREAD

**Issue by SlimeDog** [EngineHub/WorldGuard#1729]
**Versions**

WorldEdit version:
7.3.0-SNAPSHOT+5647-476342a

WorldGuard version:
WorldGuard-bukkit-7.0.5-b2104

Platform version:
Spigot 1.16.5-3007
or
Paper 1.16.5-466

**Describe the bug**

On start-up
```
[11:09:17] [Server thread/ERROR]: Could not load 'plugins/WorldGuard-bukkit-7.0.5-b2104.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: com/sk89q/worldguard/bukkit/bstats/bukkit/Metrics$CustomChart
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:139) ~[spigot-1.16.5-3007.jar:3007-Spigot-cd23533-a82b212]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:394) ~[spigot-1.16.5-3007.jar:3007-Spigot-cd23533-a82b212]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:301) ~[spigot-1.16.5-3007.jar:3007-Spigot-cd23533-a82b212]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:382) ~[spigot-1.16.5-3007.jar:3007-Spigot-cd23533-a82b212]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:185) ~[spigot-1.16.5-3007.jar:3007-Spigot-cd23533-a82b212]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:809) ~[spigot-1.16.5-3007.jar:3007-Spigot-cd23533-a82b212]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.5-3007.jar:3007-Spigot-cd23533-a82b212]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NoClassDefFoundError: com/sk89q/worldguard/bukkit/bstats/bukkit/Metrics$CustomChart
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:398) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot-1.16.5-3007.jar:3007-Spigot-cd23533-a82b212]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigot-1.16.5-3007.jar:3007-Spigot-cd23533-a82b212]
        ... 7 more
Caused by: java.lang.ClassNotFoundException: com.sk89q.worldguard.bukkit.bstats.bukkit.Metrics$CustomChart
        at java.net.URLClassLoader.findClass(URLClassLoader.java:471) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:167) ~[spigot-1.16.5-3007.jar:3007-Spigot-cd23533-a82b212]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:96) ~[spigot-1.16.5-3007.jar:3007-Spigot-cd23533-a82b212]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:398) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot-1.16.5-3007.jar:3007-Spigot-cd23533-a82b212]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigot-1.16.5-3007.jar:3007-Spigot-cd23533-a82b212]
```

**To Reproduce**

1. Update WG from WorldGuard-bukkit-7.0.5-b2103
2. Start server

**Comment by SlimeDog** [comment]
Confirmed fixed with build 2105. Thanks.
