### ISSUE TITLE
Could not pass event StructureGrowEvent to WorldGuard v7.0.6-beta1 : no idea of the impact of this error

### ISSUE THREAD

**Issue by Uharn** [EngineHub/WorldGuard#1851]
**Versions**
WorldGuard version:version: 7.0.6-beta1

Platform version: Airplane 1.17.1

**Describe the bug**
Error spamming in console:
[18:01:14 ERROR]: Could not pass event StructureGrowEvent to WorldGuard v7.0.6-beta1+0b66f3e
java.lang.IllegalArgumentException: null
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:127) ~[patched_1.17.1.jar:git-Airplane-95]
        at com.sk89q.worldguard.bukkit.event.block.AbstractBlockEvent.<init>(AbstractBlockEvent.java:70) ~[worldguard-bukkit-7.0.6-beta1-dist.jar:?]
        at com.sk89q.worldguard.bukkit.event.block.PlaceBlockEvent.<init>(PlaceBlockEvent.java:45) ~[worldguard-bukkit-7.0.6-beta1-dist.jar:?]
        at com.sk89q.worldguard.bukkit.listener.EventAbstractionListener.onStructureGrowEvent(EventAbstractionListener.java:270) ~[worldguard-bukkit-7.0.6-beta1-dist.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor398.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Airplane-95]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.17.1.jar:git-Airplane-95]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Airplane-95]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630) ~[patched_1.17.1.jar:git-Airplane-95]
        at net.minecraft.world.level.block.SaplingBlock.randomTick(SaplingBlock.java:60) ~[app:?]
        at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.randomTick(BlockBehaviour.java:921) ~[app:?]
        at net.minecraft.server.level.ServerLevel.tickChunk(ServerLevel.java:950) ~[app:?]
        at net.minecraft.server.level.ServerChunkCache.tickChunks(ServerChunkCache.java:1049) ~[app:?]
        at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:934) ~[app:?]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:731) ~[app:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1619) ~[patched_1.17.1.jar:git-Airplane-95]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:492) ~[patched_1.17.1.jar:git-Airplane-95]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1475) ~[patched_1.17.1.jar:git-Airplane-95]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1274) ~[patched_1.17.1.jar:git-Airplane-95]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Airplane-95]
        at java.lang.Thread.run(Thread.java:831) ~[?:?]

**To Reproduce**
The error is trown like every 30 minutes on one server (but not on other survival server having the same config in my bungee network

**Expected behavior**
No error in console

**Additional context**
unfortunately I cannot find the source in loaded chunks
I use crashclaim plugin if that can help

**Comment by me4502** [comment]
You're using a server platform known to cause issues (Airplane) and an beta version of the plugin. Use Paper and an up to date WorldGuard.

**Comment by JOO200** [comment]
It might still be a bug: 
The block list from StructureGrowEvent is mutable but WorldGuard doesn't check for empty block lists. 

Some plugin could remove all blocks from that list before WorldGuard and WG will raise that exception.
