### ISSUE TITLE
error occured while enabling worldguard

### ISSUE THREAD

**Issue by gaggara** [EngineHub/WorldGuard#1893]
### WorldEdit Version

7.2.10

### WorldGuard Version

7.0.5

### Platform Version

lastest spigot 1.16.5

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of WorldGuard compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

java.lang.IllegalArgumentException: Invalid flag name used

at com.sk89q.worldguard.protection.flags.Flag.<init>(Flag.java:59) ~[?:?]

at com.sk89q.worldguard.protection.flags.Flag.<init>(Flag.java:74) ~[?:?]

at com.sk89q.worldguard.protection.flags.registry.UnknownFlag.<init>(UnknownFlag.java:31) ~[?:?]

at com.sk89q.worldguard.protection.flags.registry.SimpleFlagRegistry.getOrCreate(SimpleFlagRegistry.java:117) ~[?:?]

at com.sk89q.worldguard.protection.flags.registry.SimpleFlagRegistry.unmarshal(SimpleFlagRegistry.java:136) ~[?:?]

at com.sk89q.worldguard.protection.managers.storage.file.YamlRegionFile.setFlags(YamlRegionFile.java:296) ~[?:?]

at com.sk89q.worldguard.protection.managers.storage.file.YamlRegionFile.loadAll(YamlRegionFile.java:167) ~[?:?]

at com.sk89q.worldguard.protection.managers.RegionManager.load(RegionManager.java:100) ~[?:?]

at com.sk89q.worldguard.protection.managers.RegionContainerImpl.createAndLoad(RegionContainerImpl.java:138) ~[?:?]

at com.sk89q.worldguard.protection.managers.RegionContainerImpl.load(RegionContainerImpl.java:115) ~[?:?]

at com.sk89q.worldguard.bukkit.BukkitRegionContainer.load(BukkitRegionContainer.java:117) ~[?:?]

at com.sk89q.worldguard.protection.regions.RegionContainer.loadWorlds(RegionContainer.java:175) ~[?:?]

at com.sk89q.worldguard.protection.regions.RegionContainer.initialize(RegionContainer.java:64) ~[?:?]

at com.sk89q.worldguard.bukkit.BukkitRegionContainer.initialize(BukkitRegionContainer.java:66) ~[?:?]

at com.sk89q.worldguard.bukkit.BukkitWorldGuardPlatform.load(BukkitWorldGuardPlatform.java:143) ~[?:?]

at com.sk89q.worldguard.WorldGuard.setup(WorldGuard.java:91) ~[?:?]

at com.sk89q.worldguard.bukkit.WorldGuardPlugin.onEnable(WorldGuardPlugin.java:142) ~[?:?]

at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]

at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]

at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]

at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:492) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]

at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:406) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]

at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:554) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]

at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:257) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]

at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:928) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]

at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:273) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]

at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

### Expected Behavior

WorldGuard loads

### Reproduction Steps

change regions.yml's greetings flag on every region

**Comment by JOO200** [comment]
Don't touch the regions.yml file.
Use the in-game command to modify flags. Your region.yml is invalid now and WorldGuard can't load it.

Beside of that - your Minecraft and WorldGuard version is outdated.
