### ISSUE TITLE
Could not pass event PlayerMoveEvent to WorldGuard

### ISSUE THREAD

**Issue by mrcoffee1026** [EngineHub/WorldGuard#1920]
### WorldEdit Version

 FastAsyncWorldEdit-196

### WorldGuard Version

7.0.7+216b061

### Platform Version

 Paper version git-Paper-379 (MC: 1.18.2)

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of WorldGuard compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Trying to use the "godmode: allowed" flag in a region.  When player leaves the region godmode needs to be released from that player.  It seems to do so fine if the player walks out of the region, however if they fly or warp out of the region, they are still invincible.  I've attempted adding "console-command-on-exit: /ungod %playername%" in order to remedy this, but even that doesn't have the desired effect (although the command itself is run properly).  Not certain but it might be due to the following error which is spammed in the console while a player is crossing the border of the region:

`[18:54:48] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to WorldGuard v7.0.7+216b061
java.lang.NullPointerException: Cannot invoke "com.earth2me.essentials.User.isGodModeEnabled()" because "user" is null
	at net.goldtreeservers.worldguardextraflags.wg.handlers.GodmodeFlagHandler.handleValue(GodmodeFlagHandler.java:87) ~[WorldGuardExtraFlags.jar:?]
	at net.goldtreeservers.worldguardextraflags.wg.handlers.GodmodeFlagHandler.onSetValue(GodmodeFlagHandler.java:55) ~[WorldGuardExtraFlags.jar:?]
	at net.goldtreeservers.worldguardextraflags.wg.handlers.GodmodeFlagHandler.onSetValue(GodmodeFlagHandler.java:22) ~[WorldGuardExtraFlags.jar:?]
	at com.sk89q.worldguard.session.handler.FlagValueChangeHandler.onCrossBoundary(FlagValueChangeHandler.java:61) ~[worldguard-bukkit-7.0.7-dist.jar:?]
	at com.sk89q.worldguard.bukkit.session.TimedHandlerFactory$TimedHandler.onCrossBoundary(TimedHandlerFactory.java:107) ~[worldguard-bukkit-7.0.7-dist.jar:?]
	at com.sk89q.worldguard.session.Session.testMoveTo(Session.java:220) ~[worldguard-bukkit-7.0.7-dist.jar:?]
	at com.sk89q.worldguard.session.Session.testMoveTo(Session.java:180) ~[worldguard-bukkit-7.0.7-dist.jar:?]
	at com.sk89q.worldguard.bukkit.listener.PlayerMoveListener.onPlayerMove(PlayerMoveListener.java:105) ~[worldguard-bukkit-7.0.7-dist.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor348.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:git-Paper-379]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:669) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleMovePlayer(ServerGamePacketListenerImpl.java:1505) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket.handle(ServerboundMovePlayerPacket.java:29) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket$PosRot.handle(ServerboundMovePlayerPacket.java:88) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.2.jar:git-Paper-379]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1400) ~[paper-1.18.2.jar:git-Paper-379]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188) ~[paper-1.18.2.jar:git-Paper-379]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1377) ~[paper-1.18.2.jar:git-Paper-379]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1370) ~[paper-1.18.2.jar:git-Paper-379]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1348) ~[paper-1.18.2.jar:git-Paper-379]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1230) ~[paper-1.18.2.jar:git-Paper-379]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-379]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
`

### Expected Behavior

Godmode needs to be released when player leaves the region they are in.

### Reproduction Steps

1. Enable flag "godmode: allowed" or "invincible: true" for region, then attempt a variety of ways of departing this region and ensure that you are still not invincieble.
2. Warping or flying out of the region will result in you still being invincible.

**Comment by me4502** [comment]
Don't lie in the issue template, and that's not even a WorldGuard error

**Comment by ahsaneajz** [comment]
i am also having this issue

**Comment by me4502** [comment]
As I said over a year ago when this issue was made, this is not related to WorldGuard, it's an Essentials error
