### ISSUE TITLE
Server Crashes on entering chunk

### ISSUE THREAD

**Issue by Thangsss** [EngineHub/WorldGuard#1982]
### WorldEdit Version

7.2.12+6240-87f4ae1

### WorldGuard Version

7.0.8-beta+01+cbb3b7

### Platform Version

git-paper-238

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of WorldGuard compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [x] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Server crashing when loading a certain chunk
`[19:00:37 ERROR]: Could not pass event ChunkLoadEvent to WorldGuard v7.0.8-beta-01+cbb2ba7
java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or process/resource limits reached
        at java.lang.Thread.start0(Native Method) ~[?:?]
        at java.lang.Thread.start(Thread.java:802) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:945) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1362) ~[?:?]
        at com.google.common.util.concurrent.MoreExecutors$ListeningDecorator.execute(MoreExecutors.java:619) ~[guava-31.0.1-jre.jar:?]
        at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:123) ~[?:?]
        at com.google.common.util.concurrent.AbstractListeningExecutorService.submit(AbstractListeningExecutorService.java:58) ~[guava-31.0.1-jre.jar:?]
        at com.sk89q.worldguard.protection.managers.index.ChunkHashTable.get(ChunkHashTable.java:100) ~[worldguard-bukkit-7.0.8-beta-01-dist.jar:?]
        at com.sk89q.worldguard.protection.managers.index.ChunkHashTable.getOrCreate(ChunkHashTable.java:114) ~[worldguard-bukkit-7.0.8-beta-01-dist.jar:?]
        at com.sk89q.worldguard.protection.managers.index.ChunkHashTable.bias(ChunkHashTable.java:166) ~[worldguard-bukkit-7.0.8-beta-01-dist.jar:?]
        at com.sk89q.worldguard.protection.managers.RegionManager.loadChunk(RegionManager.java:157) ~[worldguard-bukkit-7.0.8-beta-01-dist.jar:?]
        at com.sk89q.worldguard.bukkit.BukkitRegionContainer$1.onChunkLoad(BukkitRegionContainer.java:83) ~[worldguard-bukkit-7.0.8-beta-01-dist.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:git-Paper-238]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.world.level.chunk.LevelChunk.loadCallback(LevelChunk.java:916) ~[?:?]
        at net.minecraft.world.level.chunk.LevelChunk.onChunkLoad(LevelChunk.java:868) ~[?:?]
        at io.papermc.paper.chunk.system.scheduling.NewChunkHolder.handleFullStatusChange(NewChunkHolder.java:1311) ~[paper-1.19.2.jar:git-Paper-238]
        at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.processPendingFullUpdate(ChunkHolderManager.java:1050) ~[paper-1.19.2.jar:git-Paper-238]
        at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.processTicketUpdates(ChunkHolderManager.java:1034) ~[paper-1.19.2.jar:git-Paper-238]
        at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.processTicketUpdates(ChunkHolderManager.java:919) ~[paper-1.19.2.jar:git-Paper-238]
        at net.minecraft.server.level.ServerChunkCache.runDistanceManagerUpdates(ServerChunkCache.java:582) ~[?:?]
        at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.pollTask(ServerChunkCache.java:1000) ~[?:?]
        at net.minecraft.server.level.ServerChunkCache.pollTask(ServerChunkCache.java:578) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1329) ~[paper-1.19.2.jar:git-Paper-238]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.2.jar:git-Paper-238]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1389) ~[paper-1.19.2.jar:git-Paper-238]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.2.jar:git-Paper-238]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-238]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[228.660s][warning][os,thread] Failed to start thread "Unknown thread" - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
[228.660s][warning][os,thread] Failed to start the native thread for java.lang.Thread "WorldGuard Region Chunk Table - HallowedMC_the_end"`

### Expected Behavior

No server crashes

### Reproduction Steps

1. ...
2. ...
unsure how to reproduce the behavior

### Optional WorldGuard-Report

https://paste.enginehub.org/ZdzKJNyDF.report

**Comment by JOO200** [comment]
That's a limitation from your server/host:
`java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or process/resource limits reached`
Make sure your server can create enough threads and no other plugin is creating too much threads.
