### ISSUE TITLE
Bur or incompatibility w/ OI

### ISSUE THREAD

**Issue by molor** [EngineHub/WorldGuard#1987]
### WorldEdit Version

7.2.14-SNAPSHOT+6354-632470b

### WorldGuard Version

7.0.8-SNAPSHOT+2221-1729e5e

### Platform Version

git-Paper-"fe88107" (MC: 1.19.4)

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [ ] I am using a version of WorldGuard compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

There's probably a conflict with https://github.com/Jikoo/OpenInv
Sometimes (not with every player) if I use `/oi player` then this exception appears in the console:
```
[14:59:27] Could not pass event InventoryOpenEvent to WorldGuard v7.0.8-SNAPSHOT+2221-1729e5e
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.World.getWorld()" because "this.entity.H" is null
        at org.bukkit.craftbukkit.v1_19_R3.entity.CraftEntity.getWorld(CraftEntity.java:539) ~[paper-1.19.4.jar:git-Paper-"fe88107"]
        at org.bukkit.craftbukkit.v1_19_R3.entity.CraftEntity.getLocation(CraftEntity.java:448) ~[paper-1.19.4.jar:git-Paper-"fe88107"]
        at com.sk89q.worldguard.bukkit.event.entity.AbstractEntityEvent.<init>(AbstractEntityEvent.java:47) ~[worldguard-bukkit-7.0.8-SNAPSHOT-dist.jar:?]
        at com.sk89q.worldguard.bukkit.event.entity.UseEntityEvent.<init>(UseEntityEvent.java:43) ~[worldguard-bukkit-7.0.8-SNAPSHOT-dist.jar:?]
        at com.sk89q.worldguard.bukkit.listener.EventAbstractionListener.handleInventoryHolderUse(EventAbstractionListener.java:1197) ~[worldguard-bukkit-7.0.8-SNAPSHOT-dist.jar:?]
        at com.sk89q.worldguard.bukkit.listener.EventAbstractionListener.onInventoryOpen(EventAbstractionListener.java:947) ~[worldguard-bukkit-7.0.8-SNAPSHOT-dist.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor277.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:git-Paper-"fe88107"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.19.4.jar:git-Paper-"fe88107"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.19.4.jar:git-Paper-"fe88107"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.event.CraftEventFactory.callInventoryOpenEvent(CraftEventFactory.java:1362) ~[paper-1.19.4.jar:git-Paper-"fe88107"]
        at org.bukkit.craftbukkit.v1_19_R3.event.CraftEventFactory.callInventoryOpenEvent(CraftEventFactory.java:1348) ~[paper-1.19.4.jar:git-Paper-"fe88107"]
        at com.lishid.openinv.internal.v1_19_R3.PlayerDataManager.openInventory(PlayerDataManager.java:172) ~[OpenInv.jar:?]
        at com.lishid.openinv.OpenInv.openInventory(OpenInv.java:281) ~[OpenInv.jar:?]
        at com.lishid.openinv.commands.OpenInvCommand.openInventory(OpenInvCommand.java:213) ~[OpenInv.jar:?]
        at com.lishid.openinv.commands.OpenInvCommand$1$1.run(OpenInvCommand.java:98) ~[OpenInv.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.4.jar:git-Paper-"fe88107"]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.4.jar:git-Paper-"fe88107"]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1482) ~[paper-1.19.4.jar:git-Paper-"fe88107"]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.19.4.jar:git-Paper-"fe88107"]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1396) ~[paper-1.19.4.jar:git-Paper-"fe88107"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.4.jar:git-Paper-"fe88107"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.19.4.jar:git-Paper-"fe88107"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### Expected Behavior

No exception in console, like before I'm updated to 1.19.

### Reproduction Steps

See **Bug Description**.

**Comment by me4502** [comment]
That error is happening inside Paper, and therefore is most likely a bug in Paper due to it being an early 1.19.4 build

**Comment by molor** [comment]
@me4502 so I'm need to report it to Paper? Thanks!
