### ISSUE TITLE
Could not pass event UseBlockEvent to WorldGuard v7.0.9-beta1

### ISSUE THREAD

**Issue by LichLord91** [EngineHub/WorldGuard#2021]
### WorldEdit Version

7.2.15

### WorldGuard Version

7.0.9 Beta 1

### Platform Version

git-Purpur-1985 (MC: 1.19.4)

### Confirmations

- [ ] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of WorldGuard compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Tons of errors in the log with UseBlockEvent  and InventoryMoveItemEvent.
 Just updated to this 7.0.9 beta 1 version and it immediately started spamming the logs with many worldguard errrors.

Logs

https://mclo.gs/bmDNuZy

### Expected Behavior

No errors

### Reproduction Steps

Update to latest Worldguard beta release
Start server
Errors spam logs 

### Optional WorldGuard-Report

https://paste.enginehub.org/IruBNy-gR.report

### Anything Else?

The  WorldGuard-Report will show  version 7.0.8 WorldGuard as I reverted back to stop the spam log.

**Comment by Joo200** [comment]
Can reproduce this issue with 1.19.4 and pushed a fix for it.

Use the 7.0.8 release or the dev build from here: https://builds.enginehub.org/job/worldguard

**Comment by LichLord91** [comment]
New error related to sniffer eggs i suppose. @Joo200 


```
[20:35:34] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to WorldGuard v7.0.9-SNAPSHOT+2252-fba8333
java.lang.NoSuchFieldError: SNIFFER_EGG
        at com.sk89q.worldguard.bukkit.listener.WorldGuardPlayerListener.handlePhysicalInteract(WorldGuardPlayerListener.java:310) ~[?:?]
        at com.sk89q.worldguard.bukkit.listener.WorldGuardPlayerListener.onPlayerInteract(WorldGuardPlayerListener.java:212) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor137.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:git-Purpur-1985]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:564) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at org.bukkit.craftbukkit.v1_19_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:521) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at org.bukkit.craftbukkit.v1_19_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:516) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at org.bukkit.craftbukkit.v1_19_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:511) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.world.level.block.BlockPressurePlateBinary.b(BlockPressurePlateBinary.java:71) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.world.level.block.BlockPressurePlateAbstract.a(BlockPressurePlateAbstract.java:87) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.world.level.block.BlockPressurePlateAbstract.a(BlockPressurePlateAbstract.java:80) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.world.level.block.state.BlockBase$BlockData.a(BlockBase.java:1069) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.world.entity.Entity.aL(Entity.java:1570) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.world.entity.Entity.ay(Entity.java:1274) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.world.entity.Entity.a(Entity.java:1201) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1595) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.network.protocol.game.PacketPlayInFlying.a(PacketPlayInFlying.java:29) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.network.protocol.game.PacketPlayInFlying$PacketPlayInPositionLook.a(PacketPlayInFlying.java:88) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$0(PlayerConnectionUtils.java:51) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1369) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.server.MinecraftServer.bi(MinecraftServer.java:1346) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1339) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.util.thread.IAsyncTaskHandler.br(IAsyncTaskHandler.java:114) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1455) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1195) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by Joo200** [comment]
Yea... Backwards compatibility is a PITA. We will remove the compatibility with 1.19.4 instead of fixing that.

Please stick to the 7.0.8 version if you want to use 1.19.4

**Comment by LichLord91** [comment]
Sounds good just letting 1.20 cook a bit before switching to it myself. Some of my other plug-ins haven't updated too so no rush here I'll revert back to the other version then. :)
