### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by michael-b-jordan** [EngineHub/WorldGuard#2024]
### WorldEdit Version

7.2.15+6463-5ca4dff

### WorldGuard Version

7.0.8

### Platform Version

This server is running Pufferfish version git-Pufferfish-15 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 30537a0 on HEAD) You are on the latest version! Previous version: git-Pufferfish-73 (MC: 1.19.4)

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of WorldGuard compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

`[01:41:17] [Server thread/ERROR]: Error occurred while enabling WorldGuard v7.0.8+33cdb4a (Is it up to date?)
java.lang.NoSuchMethodError: org.yaml.snakeyaml.constructor.SafeConstructor: method 'void <init>()' not found
	at com.sk89q.worldguard.protection.managers.storage.file.YamlRegionFile.<clinit>(YamlRegionFile.java:92) ~[worldguard-bukkit-7.0.8-dist.jar:?]
	at com.sk89q.worldguard.protection.managers.storage.file.DirectoryYamlDriver.get(DirectoryYamlDriver.java:79) ~[worldguard-bukkit-7.0.8-dist.jar:?]
	at com.sk89q.worldguard.protection.managers.RegionContainerImpl.createAndLoad(RegionContainerImpl.java:136) ~[worldguard-bukkit-7.0.8-dist.jar:?]
	at com.sk89q.worldguard.protection.managers.RegionContainerImpl.load(RegionContainerImpl.java:115) ~[worldguard-bukkit-7.0.8-dist.jar:?]
	at com.sk89q.worldguard.bukkit.BukkitRegionContainer.load(BukkitRegionContainer.java:117) ~[worldguard-bukkit-7.0.8-dist.jar:?]
	at com.sk89q.worldguard.protection.regions.RegionContainer.loadWorlds(RegionContainer.java:175) ~[worldguard-bukkit-7.0.8-dist.jar:?]
	at com.sk89q.worldguard.protection.regions.RegionContainer.initialize(RegionContainer.java:64) ~[worldguard-bukkit-7.0.8-dist.jar:?]
	at com.sk89q.worldguard.bukkit.BukkitRegionContainer.initialize(BukkitRegionContainer.java:66) ~[worldguard-bukkit-7.0.8-dist.jar:?]
	at com.sk89q.worldguard.bukkit.BukkitWorldGuardPlatform.load(BukkitWorldGuardPlatform.java:143) ~[worldguard-bukkit-7.0.8-dist.jar:?]
	at com.sk89q.worldguard.WorldGuard.setup(WorldGuard.java:91) ~[worldguard-bukkit-7.0.8-dist.jar:?]
	at com.sk89q.worldguard.bukkit.WorldGuardPlugin.onEnable(WorldGuardPlugin.java:151) ~[worldguard-bukkit-7.0.8-dist.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[pufferfish-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[pufferfish-1.20.1.jar:git-Pufferfish-15]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[pufferfish-1.20.1.jar:git-Pufferfish-15]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[pufferfish-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:636) ~[pufferfish-1.20.1.jar:git-Pufferfish-15]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:547) ~[pufferfish-1.20.1.jar:git-Pufferfish-15]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:638) ~[pufferfish-1.20.1.jar:git-Pufferfish-15]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[pufferfish-1.20.1.jar:git-Pufferfish-15]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:310) ~[pufferfish-1.20.1.jar:git-Pufferfish-15]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1103) ~[pufferfish-1.20.1.jar:git-Pufferfish-15]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[pufferfish-1.20.1.jar:git-Pufferfish-15]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[01:41:17] [Server thread/INFO]: [WorldGuard] Disabling WorldGuard v7.0.8+33cdb4a
[01:41:17] [Server thread/INFO]: [WorldGuard] Shutting down executor and cancelling any pending tasks...`

### Expected Behavior

The plugin startups properly

### Reproduction Steps

1. Startup server

**Comment by Joo200** [comment]
Your WorldGuard version doesn't support MC 1.20.1. use the beta release from WorldGuard.
