### ISSUE TITLE
Error message on server disable

### ISSUE THREAD

**Issue by Waterman1001** [EngineHub/WorldGuard#2039]
### WorldEdit Version

7.2.16

### WorldGuard Version

7.0.9

### Platform Version

git-Paper-241 (MC: 1.20.2)

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of WorldGuard compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

The following error occurs when I stop my server:

```
[00:49:53 INFO]: [WorldGuard] Disabling WorldGuard v7.0.9+5934e49
[00:49:53 INFO]: [WorldGuard] Shutting down executor and cancelling any pending tasks...
[00:49:53 ERROR]: Error occurred (in the plugin loader) while disabling WorldGuard v7.0.9+5934e49 (Is it up to date?)
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.NullPointerException: Cannot invoke "ru.tehkode.permissions.backends.PermissionBackend.getUserData(String)" because "this.backend" is null
at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2086) ~[guava-32.1.2-jre.jar:?]
at com.google.common.cache.LocalCache.get(LocalCache.java:4012) ~[guava-32.1.2-jre.jar:?]
at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4035) ~[guava-32.1.2-jre.jar:?]
at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5013) ~[guava-32.1.2-jre.jar:?]
at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5020) ~[guava-32.1.2-jre.jar:?]
at com.sk89q.worldguard.session.AbstractSessionManager.hasBypass(AbstractSessionManager.java:149) ~[worldguard-bukkit-7.0.9-dist.jar:?]
at com.sk89q.worldguard.bukkit.session.BukkitSessionManager.hasBypass(BukkitSessionManager.java:86) ~[worldguard-bukkit-7.0.9-dist.jar:?]
at com.sk89q.worldguard.session.handler.ExitFlag.onAbsentValue(ExitFlag.java:96) ~[worldguard-bukkit-7.0.9-dist.jar:?]
at com.sk89q.worldguard.session.handler.ExitFlag.onAbsentValue(ExitFlag.java:33) ~[worldguard-bukkit-7.0.9-dist.jar:?]
at com.sk89q.worldguard.session.handler.FlagValueChangeHandler.onClearValue(FlagValueChangeHandler.java:86) ~[worldguard-bukkit-7.0.9-dist.jar:?]
at com.sk89q.worldguard.session.handler.FlagValueChangeHandler.uninitialize(FlagValueChangeHandler.java:50) ~[worldguard-bukkit-7.0.9-dist.jar:?]
at com.sk89q.worldguard.session.Session.uninitialize(Session.java:134) ~[worldguard-bukkit-7.0.9-dist.jar:?]
at com.sk89q.worldguard.bukkit.session.BukkitSessionManager.shutdown(BukkitSessionManager.java:92) ~[worldguard-bukkit-7.0.9-dist.jar:?]
at com.sk89q.worldguard.bukkit.BukkitWorldGuardPlatform.unload(BukkitWorldGuardPlatform.java:149) ~[worldguard-bukkit-7.0.9-dist.jar:?]
at com.sk89q.worldguard.WorldGuard.disable(WorldGuard.java:206) ~[worldguard-bukkit-7.0.9-dist.jar:?]
at com.sk89q.worldguard.bukkit.WorldGuardPlugin.onDisable(WorldGuardPlugin.java:266) ~[worldguard-bukkit-7.0.9-dist.jar:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:283) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:224) ~[paper-1.20.2.jar:git-Paper-241]
at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugins(PaperPluginInstanceManager.java:148) ~[paper-1.20.2.jar:git-Paper-241]
at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugins(PaperPluginManagerImpl.java:92) ~[paper-1.20.2.jar:git-Paper-241]
at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:528) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.v1_20_R2.CraftServer.disablePlugins(CraftServer.java:575) ~[paper-1.20.2.jar:git-Paper-241]
at net.minecraft.server.MinecraftServer.stopServer(MinecraftServer.java:930) ~[paper-1.20.2.jar:git-Paper-241]
at net.minecraft.server.dedicated.DedicatedServer.stopServer(DedicatedServer.java:818) ~[paper-1.20.2.jar:git-Paper-241]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1195) ~[paper-1.20.2.jar:git-Paper-241]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-241]
at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "ru.tehkode.permissions.backends.PermissionBackend.getUserData(String)" because "this.backend" is null
at ru.tehkode.permissions.PermissionManager.getUser(PermissionManager.java:220) ~[PermissionsEx-1.23.4.jar:?]
at ru.tehkode.permissions.PermissionManager.getUser(PermissionManager.java:210) ~[PermissionsEx-1.23.4.jar:?]
at ru.tehkode.permissions.PermissionManager.has(PermissionManager.java:148) ~[PermissionsEx-1.23.4.jar:?]
at com.sk89q.wepif.PermissionsExResolver.hasPermission(PermissionsExResolver.java:68) ~[worldedit-bukkit-7.2.16.jar:?]
at com.sk89q.wepif.PermissionsResolverManager.hasPermission(PermissionsResolverManager.java:170) ~[worldedit-bukkit-7.2.16.jar:?]
at com.sk89q.worldguard.bukkit.WorldGuardPlugin.hasPermission(WorldGuardPlugin.java:360) ~[worldguard-bukkit-7.0.9-dist.jar:?]
at com.sk89q.worldguard.bukkit.BukkitPlayer.hasPermission(BukkitPlayer.java:219) ~[worldguard-bukkit-7.0.9-dist.jar:?]
at com.sk89q.worldguard.session.AbstractSessionManager.lambda$static$0(AbstractSessionManager.java:62) ~[worldguard-bukkit-7.0.9-dist.jar:?]
at com.sk89q.worldguard.session.AbstractSessionManager.lambda$new$1(AbstractSessionManager.java:68) ~[worldguard-bukkit-7.0.9-dist.jar:?]
at com.google.common.cache.CacheLoader$FunctionToCacheLoader.load(CacheLoader.java:169) ~[guava-32.1.2-jre.jar:?]
at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3571) ~[guava-32.1.2-jre.jar:?]
at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2313) ~[guava-32.1.2-jre.jar:?]
at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2190) ~[guava-32.1.2-jre.jar:?]
at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2080) ~[guava-32.1.2-jre.jar:?]
... 26 more
```

### Expected Behavior

I expected the error to not occur

### Reproduction Steps

1. Stop the server
2. Get an error message

### Anything Else?

Hopefully it can be fixed! :D

**Comment by wizjany** [comment]
nothing we can do here, this is just due to how bukkit disables plugins at shutdown.

**Comment by Waterman1001** [comment]
Ah, I see. Thank you for your message. That is unfortunate...
