### ISSUE TITLE
Problem when stopping server

### ISSUE THREAD

**Issue by smscentras** [EngineHub/WorldGuard#2040]
### WorldEdit Version

FastAsyncWorldEdit-Bukkit-2.8.2-SNAPSHOT-596

### WorldGuard Version

worldguard-bukkit-7.0.9-dist

### Platform Version

Paper 1.20.2

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of WorldGuard compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

When reloading server,- sometimes error

### Expected Behavior

[04:42:16 ERROR]: Error occurred (in the plugin loader) while disabling WorldGuard v7.0.9+5934e49 (Is it up to date?)
java.lang.IllegalStateException: zip file closed
        at java.util.zip.ZipFile.ensureOpen(ZipFile.java:840) ~[?:?]
        at java.util.zip.ZipFile.getEntry(ZipFile.java:339) ~[?:?]
        at java.util.jar.JarFile.getEntry(JarFile.java:517) ~[?:?]
        at java.util.jar.JarFile.getJarEntry(JarFile.java:472) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:195) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:155) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:150) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at net.goldtreeservers.worldguardextraflags.wg.handlers.GlideFlagHandler.onAbsentValue(GlideFlagHandler.java:57) ~[WorldGuardExtraFlags.4.2.2.jar:?]
        at net.goldtreeservers.worldguardextraflags.wg.handlers.GlideFlagHandler.onAbsentValue(GlideFlagHandler.java:18) ~[WorldGuardExtraFlags.4.2.2.jar:?]
        at com.sk89q.worldguard.session.handler.FlagValueChangeHandler.onClearValue(FlagValueChangeHandler.java:86) ~[worldguard-bukkit-7.0.9-dist.jar:?]
        at com.sk89q.worldguard.session.handler.FlagValueChangeHandler.uninitialize(FlagValueChangeHandler.java:50) ~[worldguard-bukkit-7.0.9-dist.jar:?]
        at com.sk89q.worldguard.session.Session.uninitialize(Session.java:134) ~[worldguard-bukkit-7.0.9-dist.jar:?]
        at com.sk89q.worldguard.bukkit.session.BukkitSessionManager.shutdown(BukkitSessionManager.java:92) ~[worldguard-bukkit-7.0.9-dist.jar:?]
        at com.sk89q.worldguard.bukkit.BukkitWorldGuardPlatform.unload(BukkitWorldGuardPlatform.java:149) ~[worldguard-bukkit-7.0.9-dist.jar:?]
        at com.sk89q.worldguard.WorldGuard.disable(WorldGuard.java:206) ~[worldguard-bukkit-7.0.9-dist.jar:?]
        at com.sk89q.worldguard.bukkit.WorldGuardPlugin.onDisable(WorldGuardPlugin.java:266) ~[worldguard-bukkit-7.0.9-dist.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:283) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:224) ~[paper-1.20.2.jar:git-Paper-246]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugins(PaperPluginInstanceManager.java:148) ~[paper-1.20.2.jar:git-Paper-246]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugins(PaperPluginManagerImpl.java:92) ~[paper-1.20.2.jar:git-Paper-246]
        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:528) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.disablePlugins(CraftServer.java:575) ~[paper-1.20.2.jar:git-Paper-246]
        at net.minecraft.server.MinecraftServer.stopServer(MinecraftServer.java:930) ~[paper-1.20.2.jar:git-Paper-246]
        at net.minecraft.server.dedicated.DedicatedServer.stopServer(DedicatedServer.java:818) ~[paper-1.20.2.jar:git-Paper-246]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1195) ~[paper-1.20.2.jar:git-Paper-246]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-246]
        at java.lang.Thread.run(Thread.java:842) ~[?:?]

### Reproduction Steps

1. Reloading server

**Comment by me4502** [comment]
Don’t lie on the issue template, and this error is entirely unrelated to WorldGuard - https://madelinemiller.dev/blog/minecraft-zip-file-closed/

**Comment by smscentras** [comment]
When stop server, sometimes message:
Error occurred (in the plugin loader) while disabling WorldGuard v7.0.9+5934e49 (Is it up to date?)

**Comment by smscentras** [comment]
Who lying? what's wrong with you, man?
