### ISSUE TITLE
NPE: packNames is null

### ISSUE THREAD

**Issue by SlimeDog** [EngineHub/WorldGuard#2047]
### WorldEdit Version

7.3.0-SNAPSHOT+6612-ebf355f

### WorldGuard Version

7.0.10-SNAPSHOT+2260-c7319f1

### Platform Version

Paper version git-Paper-324 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 28abbaa)

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of WorldGuard compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

On player teleport to a different world, using the same resourcepack
```
[06:17:33] [Server thread/ERROR]: Could not pass event PlayerTeleportEvent to WorldGuard v7.0.10-SNAPSHOT+2260-c7319f1
java.lang.NullPointerException: Cannot invoke "String.split(String)" because "packNames" is null
        at de.themoep.resourcepacksplugin.bukkit.worldguard.WorldGuardHandler.handleBorderCross(WorldGuardHandler.java:51) ~[ForceResourcepacks-1.12.0.jar:?]
        at de.themoep.resourcepacksplugin.bukkit.worldguard.WorldGuard7Handler.onCrossBoundary(WorldGuard7Handler.java:135) ~[ForceResourcepacks-1.12.0.jar:?]
        at com.sk89q.worldguard.session.Session.testMoveTo(Session.java:235) ~[WorldGuard-bukkit-7.0.10-b2260.jar:?]
        at com.sk89q.worldguard.session.Session.testMoveTo(Session.java:195) ~[WorldGuard-bukkit-7.0.10-b2260.jar:?]
        at com.sk89q.worldguard.bukkit.listener.WorldGuardPlayerListener.onPlayerTeleport(WorldGuardPlayerListener.java:404) ~[WorldGuard-bukkit-7.0.10-b2260.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor164.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:git-Paper-324]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.4.jar:git-Paper-324]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.4.jar:git-Paper-324]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.entity.CraftPlayer.teleport(CraftPlayer.java:1378) ~[paper-1.20.4.jar:git-Paper-324]
        at org.bukkit.craftbukkit.v1_20_R3.entity.CraftPlayer.teleport(CraftPlayer.java:1276) ~[paper-1.20.4.jar:git-Paper-324]
        at org.bukkit.craftbukkit.v1_20_R3.entity.CraftEntity.lambda$teleportAsync$1(CraftEntity.java:1431) ~[paper-1.20.4.jar:git-Paper-324]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.4.jar:git-Paper-324]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1458) ~[paper-1.20.4.jar:git-Paper-324]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194) ~[paper-1.20.4.jar:git-Paper-324]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1435) ~[paper-1.20.4.jar:git-Paper-324]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1358) ~[paper-1.20.4.jar:git-Paper-324]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1509) ~[paper-1.20.4.jar:git-Paper-324]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1214) ~[paper-1.20.4.jar:git-Paper-324]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[paper-1.20.4.jar:git-Paper-324]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

### Expected Behavior

clean teleport

### Reproduction Steps

1. connect to server
2. teleport to different world

**Comment by SlimeDog** [comment]
Apparently an issue with ForceResourcepacks.
