### ISSUE TITLE
java.lang.IllegalStateException: zip file closed

### ISSUE THREAD

**Issue by cdjohnson87** [EngineHub/WorldGuard#2055]
### WorldEdit Version

7.2.17

### WorldGuard Version

7.0.9

### Platform Version

paper 1.20.2-318

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of WorldGuard compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Plugin runs fine until some random amount of time later while trying to run worldedit commands, the plugin returns an error that states "Please report this error".  Ive provided the console log in the additional context box below.

### Expected Behavior

running //replace expected the comamnd to run and replace the blocks i referenced in the command

### Reproduction Steps

1. server started normally without issue, plugin runs normally without issue
2. a random time period later, running commands that have worked are not longer working (ran //replace command)
3. in game message says to report this error and to check the console

### Anything Else?

Console log:
[20:17:47 INFO]: Please report this error: [See console]
[20:17:47 INFO]: java.lang.IllegalStateException: zip file closed
[20:17:47 ERROR]: An unexpected error while handling a WorldEdit command
java.lang.IllegalStateException: zip file closed
        at java.util.zip.ZipFile.ensureOpen(ZipFile.java:831) ~[?:?]
        at java.util.zip.ZipFile.getEntry(ZipFile.java:330) ~[?:?]
        at java.util.jar.JarFile.getEntry(JarFile.java:518) ~[?:?]
        at java.util.jar.JarFile.getJarEntry(JarFile.java:473) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:209) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:169) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:144) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.entrypoint.classloader.group.SpigotPluginClassLoaderGroup.lookupClass(SpigotPluginClassLoaderGroup.java:43) ~[paper-1.20.2.jar:git-Paper-318]
        at io.papermc.paper.plugin.entrypoint.classloader.group.SimpleListPluginClassLoaderGroup.getClassByName(SimpleListPluginClassLoaderGroup.java:37) ~[paper-1.20.2.jar:git-Paper-318]
        at io.papermc.paper.plugin.entrypoint.classloader.group.LockingClassLoaderGroup.getClassByName(LockingClassLoaderGroup.java:34) ~[paper-1.20.2.jar:git-Paper-318]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:187) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:488) ~[?:?]
        at java.lang.Class.forName(Class.java:467) ~[?:?]
        at sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:114) ~[?:?]
        at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:125) ~[?:?]
        at sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49) ~[?:?]
        at sun.reflect.annotation.AnnotationParser.parseSig(AnnotationParser.java:441) ~[?:?]
        at sun.reflect.annotation.AnnotationParser.parseAnnotation2(AnnotationParser.java:241) ~[?:?]
        at sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:121) ~[?:?]
        at sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:73) ~[?:?]
        at java.lang.reflect.Executable.declaredAnnotations(Executable.java:625) ~[?:?]
        at java.lang.reflect.Executable.declaredAnnotations(Executable.java:623) ~[?:?]
        at java.lang.reflect.Executable.getAnnotation(Executable.java:591) ~[?:?]
        at java.lang.reflect.Method.getAnnotation(Method.java:786) ~[?:?]
        at com.sk89q.worldedit.internal.command.CommandLoggingHandler.beforeCall(CommandLoggingHandler.java:67) ~[worldedit-bukkit-7.2.17.jar:?]
        at org.enginehub.piston.internal.RegistrationUtil.listenersBeforeCall(RegistrationUtil.java:53) ~[worldedit-bukkit-7.2.17.jar:?]
        at com.sk89q.worldedit.command.WorldEditCommandsRegistration.cmd$version(WorldEditCommandsRegistration.java:170) ~[worldedit-bukkit-7.2.17.jar:?]
        at org.enginehub.piston.CommandManager.execute(CommandManager.java:157) ~[worldedit-bukkit-7.2.17.jar:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommand(PlatformCommandManager.java:497) ~[worldedit-bukkit-7.2.17.jar:?]
        at com.sk89q.worldedit.util.eventbus.MethodHandleEventHandler.dispatch(MethodHandleEventHandler.java:51) ~[worldedit-bukkit-7.2.17.jar:?]
        at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[worldedit-bukkit-7.2.17.jar:?]
        at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:193) ~[worldedit-bukkit-7.2.17.jar:?]
        at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:181) ~[worldedit-bukkit-7.2.17.jar:?]
        at com.sk89q.worldedit.bukkit.WorldEditPlugin.onCommand(WorldEditPlugin.java:390) ~[worldedit-bukkit-7.2.17.jar:?]
        at com.sk89q.bukkit.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:55) ~[worldedit-bukkit-7.2.17.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.dispatchCommand(CraftServer.java:991) ~[paper-1.20.2.jar:git-Paper-318]
        at github.scarsz.discordsrv.listeners.DiscordConsoleListener.lambda$onGuildMessageReceived$0(DiscordConsoleListener.java:95) ~[DiscordSRV-Build-1.26.2.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.2.jar:git-Paper-318]
        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1470) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1379) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1156) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-318]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by cdjohnson87** [comment]
Code provided initially was when typing /we version via discord plugin but seems the zip file closed error is showing.  the console log error resulting from //replace is as follows:

- [Thu 20:06:57 ERROR com.sk89q.worldedit.extension.platform.PlatformCommandManager] An unexpected error while handling a WorldEdit command
java.lang.IllegalStateException: zip file closed
    at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:831)
    at java.base/java.util.zip.ZipFile.getEntry(ZipFile.java:330)
    at java.base/java.util.jar.JarFile.getEntry(JarFile.java:518)
    at java.base/java.util.jar.JarFile.getJarEntry(JarFile.java:473)
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:209)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
    at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:169)
    at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:144)
    at io.papermc.paper.plugin.entrypoint.classloader.group.SpigotPluginClassLoaderGroup.lookupClass(SpigotPluginClassLoaderGroup.java:43)
    at io.papermc.paper.plugin.entrypoint.classloader.group.SimpleListPluginClassLoaderGroup.getClassByName(SimpleListPluginClassLoaderGroup.java:37)
    at io.papermc.paper.plugin.entrypoint.classloader.group.LockingClassLoaderGroup.getClassByName(LockingClassLoaderGroup.java:34)
    at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:187)
    at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
    at java.base/java.lang.Class.forName0(Native Method)
    at java.base/java.lang.Class.forName(Class.java:488)
    at java.base/java.lang.Class.forName(Class.java:467)
    at java.base/sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:114)
    at java.base/sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:125)
    at java.base/sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49)
    at java.base/sun.reflect.annotation.AnnotationParser.parseSig(AnnotationParser.java:441)
    at java.base/sun.ref

**Comment by wizjany** [comment]
https://madelinemiller.dev/blog/minecraft-zip-file-closed/
