### ISSUE TITLE
This is sometimes the case when the server is shut down

### ISSUE THREAD

**Issue by Cqmmls** [EngineHub/WorldGuard#2095]
### WorldEdit Version

7.3.3

### WorldGuard Version

7.0.9

### Platform Version

git-Leaf-"504935f"

### Confirmations

- [ ] I am using the most recent Minecraft release.
- [x] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of WorldGuard compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

[15:57:54 ERROR]: Error occurred while disabling WorldGuard v7.0.9+5934e49
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.NullPointerException: Cannot invoke "org.anjocaido.groupmanager.GroupManager.getWorldsHolder()" because "this.groupManager" is null
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2087) ~[guava-33.1.0-jre.jar:?]
        at com.google.common.cache.LocalCache.get(LocalCache.java:4019) ~[guava-33.1.0-jre.jar:?]
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4042) ~[guava-33.1.0-jre.jar:?]
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5024) ~[guava-33.1.0-jre.jar:?]
        at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5031) ~[guava-33.1.0-jre.jar:?]
        at Worldguard-7.0.9.jar/com.sk89q.worldguard.session.AbstractSessionManager.hasBypass(AbstractSessionManager.java:149) ~[Worldguard-7.0.9.jar:?]
        at Worldguard-7.0.9.jar/com.sk89q.worldguard.bukkit.session.BukkitSessionManager.hasBypass(BukkitSessionManager.java:86) ~[Worldguard-7.0.9.jar:?]
        at Worldguard-7.0.9.jar/com.sk89q.worldguard.session.handler.ExitFlag.onAbsentValue(ExitFlag.java:96) ~[Worldguard-7.0.9.jar:?]
        at Worldguard-7.0.9.jar/com.sk89q.worldguard.session.handler.ExitFlag.onAbsentValue(ExitFlag.java:33) ~[Worldguard-7.0.9.jar:?]
        at Worldguard-7.0.9.jar/com.sk89q.worldguard.session.handler.FlagValueChangeHandler.onClearValue(FlagValueChangeHandler.java:86) ~[Worldguard-7.0.9.jar:?]
        at Worldguard-7.0.9.jar/com.sk89q.worldguard.session.handler.FlagValueChangeHandler.uninitialize(FlagValueChangeHandler.java:50) ~[Worldguard-7.0.9.jar:?]
        at Worldguard-7.0.9.jar/com.sk89q.worldguard.session.Session.uninitialize(Session.java:134) ~[Worldguard-7.0.9.jar:?]
        at Worldguard-7.0.9.jar/com.sk89q.worldguard.bukkit.session.BukkitSessionManager.shutdown(BukkitSessionManager.java:92) ~[Worldguard-7.0.9.jar:?]
        at Worldguard-7.0.9.jar/com.sk89q.worldguard.bukkit.BukkitWorldGuardPlatform.unload(BukkitWorldGuardPlatform.java:149) ~[Worldguard-7.0.9.jar:?]
        at Worldguard-7.0.9.jar/com.sk89q.worldguard.WorldGuard.disable(WorldGuard.java:206) ~[Worldguard-7.0.9.jar:?]
        at Worldguard-7.0.9.jar/com.sk89q.worldguard.bukkit.WorldGuardPlugin.onDisable(WorldGuardPlugin.java:266) ~[Worldguard-7.0.9.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:290) ~[leaf-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:223) ~[leaf-1.20.4.jar:git-Leaf-"504935f"]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugins(PaperPluginInstanceManager.java:147) ~[leaf-1.20.4.jar:git-Leaf-"504935f"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugins(PaperPluginManagerImpl.java:92) ~[leaf-1.20.4.jar:git-Leaf-"504935f"]
        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:527) ~[leaf-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.disablePlugins(CraftServer.java:592) ~[leaf-1.20.4.jar:git-Leaf-"504935f"]
        at net.minecraft.server.MinecraftServer.stopServer(MinecraftServer.java:973) ~[leaf-1.20.4.jar:git-Leaf-"504935f"]
        at net.minecraft.server.dedicated.DedicatedServer.stopServer(DedicatedServer.java:853) ~[leaf-1.20.4.jar:git-Leaf-"504935f"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1275) ~[leaf-1.20.4.jar:git-Leaf-"504935f"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:308) ~[leaf-1.20.4.jar:git-Leaf-"504935f"]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "org.anjocaido.groupmanager.GroupManager.getWorldsHolder()" because "this.groupManager" is null
        at Vault.jar/net.milkbowl.vault.permission.plugins.Permission_GroupManager.playerHas(Permission_GroupManager.java:104) ~[Vault.jar:?]
        at Vault.jar/net.milkbowl.vault.permission.Permission.has(Permission.java:63) ~[Vault.jar:?]
        at Vault.jar/net.milkbowl.vault.permission.Permission.playerHas(Permission.java:132) ~[Vault.jar:?]
        at Worldedit-7.3.3.jar/com.sk89q.wepif.VaultResolver.hasPermission(VaultResolver.java:100) ~[Worldedit-7.3.3.jar:?]
        at Worldedit-7.3.3.jar/com.sk89q.wepif.PermissionsResolverManager.hasPermission(PermissionsResolverManager.java:170) ~[Worldedit-7.3.3.jar:?]
        at Worldguard-7.0.9.jar/com.sk89q.worldguard.bukkit.WorldGuardPlugin.hasPermission(WorldGuardPlugin.java:360) ~[Worldguard-7.0.9.jar:?]
        at Worldguard-7.0.9.jar/com.sk89q.worldguard.bukkit.BukkitPlayer.hasPermission(BukkitPlayer.java:219) ~[Worldguard-7.0.9.jar:?]
        at Worldguard-7.0.9.jar/com.sk89q.worldguard.session.AbstractSessionManager.lambda$static$0(AbstractSessionManager.java:62) ~[Worldguard-7.0.9.jar:?]
        at Worldguard-7.0.9.jar/com.sk89q.worldguard.session.AbstractSessionManager.lambda$new$1(AbstractSessionManager.java:68) ~[Worldguard-7.0.9.jar:?]
        at com.google.common.cache.CacheLoader$FunctionToCacheLoader.load(CacheLoader.java:169) ~[guava-33.1.0-jre.jar:?]
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3576) ~[guava-33.1.0-jre.jar:?]
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2318) ~[guava-33.1.0-jre.jar:?]
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2191) ~[guava-33.1.0-jre.jar:?]
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2081) ~[guava-33.1.0-jre.jar:?]
        ... 26 more

### Expected Behavior

I hope it shouldn't happen with this error

### Reproduction Steps

1. I'm using it with GroupManager-3.2
2. Shutting down the server sometimes happens.

**Comment by Cqmmls** [comment]
Are you sure? What is it? https://www.spigotmc.org/resources/groupmanager.38875/
