### ISSUE TITLE
Error in console, all working fine

### ISSUE THREAD

**Issue by DavidFrings** [EngineHub/WorldGuard#2098]
### WorldEdit Version

7.3.2+6779-3aca580

### WorldGuard Version

7.0.9+5934e49

### Platform Version

first Paper, now Purpur (1.21)

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of WorldGuard compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Console:
ˋˋˋˋ
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoSuchFiel
 "Server thread"]
        at worldguard-bukkit-7.0.9-dist.jar/com.sk89q.worldguard.bukkit.util.Mat
        at worldguard-bukkit-7.0.9-dist.jar/com.sk89q.worldguard.bukkit.listener
7.0.9-dist.jar:?]
        at com.google.common.base.Predicate.test(Predicate.java:79) ~[guava-32.1
        at worldguard-bukkit-7.0.9-dist.jar/com.sk89q.worldguard.bukkit.event.bl
:?]
        at worldguard-bukkit-7.0.9-dist.jar/com.sk89q.worldguard.bukkit.event.bl
        at worldguard-bukkit-7.0.9-dist.jar/com.sk89q.worldguard.bukkit.event.bl
        at worldguard-bukkit-7.0.9-dist.jar/com.sk89q.worldguard.bukkit.event.bl
        at worldguard-bukkit-7.0.9-dist.jar/com.sk89q.worldguard.bukkit.event.bl
        at worldguard-bukkit-7.0.9-dist.jar/com.sk89q.worldguard.bukkit.listener
t.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventEx
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[pa
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:7
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.jav
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEven
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(Pape
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.j
        at worldguard-bukkit-7.0.9-dist.jar/com.sk89q.worldguard.bukkit.util.Eve
        at worldguard-bukkit-7.0.9-dist.jar/com.sk89q.worldguard.bukkit.listener
0.9-dist.jar:?]
        at worldguard-bukkit-7.0.9-dist.jar/com.sk89q.worldguard.bukkit.listener
kit-7.0.9-dist.jar:?]
        at worldguard-bukkit-7.0.9-dist.jar/com.sk89q.worldguard.bukkit.listener
.9-dist.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventEx
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[pa
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:7
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.jav
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEven
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventEx
        at net.minecraft.world.entity.ambient.Bat.travel(Bat.java:89) ~[purpur-1
.21.jar:1.21-2251-ac6c312]
        at net.minecraft.world.entity.LivingEntity.aiStep(LivingEntity.java:3538
) ~[purpur-1.21.jar:1.21-2251-ac6c312]
        at net.minecraft.world.entity.Mob.aiStep(Mob.java:708) ~[purpur-1.21.jar
:1.21-2251-ac6c312]
        at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:3186)
~[purpur-1.21.jar:1.21-2251-ac6c312]
        at net.minecraft.world.entity.Mob.tick(Mob.java:469) ~[purpur-1.21.jar:1
.21-2251-ac6c312]
        at net.minecraft.world.entity.ambient.Bat.tick(Bat.java:169) ~[purpur-1.
21.jar:1.21-2251-ac6c312]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.j
ava:1257) ~[purpur-1.21.jar:1.21-2251-ac6c312]
        at net.minecraft.world.level.Level.guardEntityTick(Level.java:1029) ~[pu
rpur-1.21.jar:1.21-2251-ac6c312]
        at net.minecraft.server.level.ServerLevel.lambda$tick$6(ServerLevel.java
:757) ~[purpur-1.21.jar:1.21-2251-ac6c312]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickLis
t.java:39) ~[purpur-1.21.jar:1.21-2251-ac6c312]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:737) ~[p
urpur-1.21.jar:1.21-2251-ac6c312]
        ... 6 more
ˋˋˋˋ

### Expected Behavior

Why is this a Error in my console? (It's Red)

### Reproduction Steps

1. Start Server
2. Join Server
3. Error in Console

### Anything Else?

Can anyone help me clean my Console? Because it's spamming in there

**Comment by me4502** [comment]
you have to use the version that's labelled as supporting 1.21, not multiple versions ago
