### ISSUE TITLE
BlockFromToEvent to WorldGuard

### ISSUE THREAD

**Issue by Incluuu** [EngineHub/WorldGuard#2103]
### WorldEdit Version

worldedit-bukkit-7.3.3

### WorldGuard Version

worldguard-bukkit-7.0.10-dist

### Platform Version

This server is running Paper version 1.21-37-master@dd49fba (2024-06-24T02:08:49Z) (Implementing API version 1.21-R0.1-SNAPSHOT)

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of WorldGuard compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Could not pass event BlockFromToEvent to WorldGuard v7.0.10+d9424b1
java.lang.NoSuchFieldError: Class org.bukkit.Tag does not have member field 'org.bukkit.Tag ITEMS_MUSIC_DISCS'
        at worldguard-bukkit-7.0.10-dist.jar/com.sk89q.worldguard.bukkit.util.Materials.<clinit>(Materials.java:867) ~[worldguard-bukkit-7.0.10-dist.jar:?]
        at worldguard-bukkit-7.0.10-dist.jar/com.sk89q.worldguard.bukkit.listener.WorldGuardBlockListener.onBlockFromTo(WorldGuardBlockListener.java:114) ~[worldguard-bukkit-7.0.10-dist.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor153.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:1.21-2256-de2e7a7]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.21.jar:1.21-2256-de2e7a7]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.21.jar:1.21-2256-de2e7a7]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.world.level.material.FlowingFluid.spreadToSides(FlowingFluid.java:186) ~[purpur-1.21.jar:1.21-2256-de2e7a7]
        at net.minecraft.world.level.material.FlowingFluid.spread(FlowingFluid.java:157) ~[purpur-1.21.jar:1.21-2256-de2e7a7]
        at net.minecraft.world.level.material.FlowingFluid.tick(FlowingFluid.java:508) ~[purpur-1.21.jar:1.21-2256-de2e7a7]
        at net.minecraft.world.level.material.FluidState.tick(FluidState.java:78) ~[purpur-1.21.jar:1.21-2256-de2e7a7]
        at net.minecraft.server.level.ServerLevel.tickFluid(ServerLevel.java:1252) ~[purpur-1.21.jar:1.21-2256-de2e7a7]
        at net.minecraft.world.ticks.LevelTicks.runCollectedTicks(LevelTicks.java:192) ~[purpur-1.21.jar:1.21-2256-de2e7a7]
        at net.minecraft.world.ticks.LevelTicks.tick(LevelTicks.java:89) ~[purpur-1.21.jar:1.21-2256-de2e7a7]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:712) ~[purpur-1.21.jar:1.21-2256-de2e7a7]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1832) ~[purpur-1.21.jar:1.21-2256-de2e7a7]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:507) ~[purpur-1.21.jar:1.21-2256-de2e7a7]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1636) ~[purpur-1.21.jar:1.21-2256-de2e7a7]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1337) ~[purpur-1.21.jar:1.21-2256-de2e7a7]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:332) ~[purpur-1.21.jar:1.21-2256-de2e7a7]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[13:55:58 ERROR]: Could not pass event BlockFromToEvent to WorldGuard v7.0.10+d9424b1
java.lang.NoClassDefFoundError: Could not initialize class com.sk89q.worldguard.bukkit.util.Materials
        at worldguard-bukkit-7.0.10-dist.jar/com.sk89q.worldguard.bukkit.listener.WorldGuardBlockListener.onBlockFromTo(WorldGuardBlockListener.java:114) ~[worldguard-bukkit-7.0.10-dist.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor153.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:1.21-2256-de2e7a7]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.21.jar:1.21-2256-de2e7a7]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.21.jar:1.21-2256-de2e7a7]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.world.level.material.FlowingFluid.spreadToSides(FlowingFluid.java:186) ~[purpur-1.21.jar:1.21-2256-de2e7a7]
        at net.minecraft.world.level.material.FlowingFluid.spread(FlowingFluid.java:157) ~[purpur-1.21.jar:1.21-2256-de2e7a7]
        at net.minecraft.world.level.material.FlowingFluid.tick(FlowingFluid.java:508) ~[purpur-1.21.jar:1.21-2256-de2e7a7]
        at net.minecraft.world.level.material.FluidState.tick(FluidState.java:78) ~[purpur-1.21.jar:1.21-2256-de2e7a7]
        at net.minecraft.server.level.ServerLevel.tickFluid(ServerLevel.java:1252) ~[purpur-1.21.jar:1.21-2256-de2e7a7]
        at net.minecraft.world.ticks.LevelTicks.runCollectedTicks(LevelTicks.java:192) ~[purpur-1.21.jar:1.21-2256-de2e7a7]
        at net.minecraft.world.ticks.LevelTicks.tick(LevelTicks.java:89) ~[purpur-1.21.jar:1.21-2256-de2e7a7]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:712) ~[purpur-1.21.jar:1.21-2256-de2e7a7]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1832) ~[purpur-1.21.jar:1.21-2256-de2e7a7]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:507) ~[purpur-1.21.jar:1.21-2256-de2e7a7]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1636) ~[purpur-1.21.jar:1.21-2256-de2e7a7]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1337) ~[purpur-1.21.jar:1.21-2256-de2e7a7]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:332) ~[purpur-1.21.jar:1.21-2256-de2e7a7]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoSuchFieldError: Class org.bukkit.Tag does not have member field 'org.bukkit.Tag ITEMS_MUSIC_DISCS' [in thread "Server thread"]
        at worldguard-bukkit-7.0.10-dist.jar/com.sk89q.worldguard.bukkit.util.Materials.<clinit>(Materials.java:867) ~[worldguard-bukkit-7.0.10-dist.jar:?]
        ... 22 more

### Expected Behavior

errors in console

### Reproduction Steps

1. install wg
2. join on server
3. server version 1.21

**Comment by me4502** [comment]
neither your WorldEdit nor WorldGuard version support your MC version. use the versions actually labelled to support it.
