### ISSUE TITLE
WorldGuard spamming Error in console

### ISSUE THREAD

**Issue by DavidFrings** [EngineHub/WorldGuard#2109]
### WorldEdit Version

7.3.4+6823-6263244

### WorldGuard Version

7.0.10+d9424b1

### Platform Version

purpur-1.21-2256-de2e7a7

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of WorldGuard compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

````bash
[13:02:15] [Server thread/ERROR]: Could not pass event BlockFromToEvent to WorldGuard v7.0.10+d9424b1
java.lang.NoClassDefFoundError: Could not initialize class com.sk89q.worldguard.bukkit.util.Materials
        at worldguard-bukkit-7.0.10-dist.jar/com.sk89q.worldguard.bukkit.listener.WorldGuardBlockListener.onBlockFromTo(WorldGuardBlockListener.java:114) ~[worldguard-bukkit-7.0.10-dist.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor87.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:1.21-2256-de2e7a7]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.21.jar:1.21-2256-de2e7a7]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.21.jar:1.21-2256-de2e7a7]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.world.level.material.FlowingFluid.spread(FlowingFluid.java:146) ~[purpur-1.21.jar:1.21-2256-de2e7a7]
        at net.minecraft.world.level.material.FlowingFluid.tick(FlowingFluid.java:508) ~[purpur-1.21.jar:1.21-2256-de2e7a7]
        at net.minecraft.world.level.material.FluidState.tick(FluidState.java:78) ~[purpur-1.21.jar:1.21-2256-de2e7a7]
        at net.minecraft.server.level.ServerLevel.tickFluid(ServerLevel.java:1252) ~[purpur-1.21.jar:1.21-2256-de2e7a7]
        at net.minecraft.world.ticks.LevelTicks.runCollectedTicks(LevelTicks.java:192) ~[purpur-1.21.jar:1.21-2256-de2e7a7]
        at net.minecraft.world.ticks.LevelTicks.tick(LevelTicks.java:89) ~[purpur-1.21.jar:1.21-2256-de2e7a7]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:712) ~[purpur-1.21.jar:1.21-2256-de2e7a7]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1832) ~[purpur-1.21.jar:1.21-2256-de2e7a7]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:507) ~[purpur-1.21.jar:1.21-2256-de2e7a7]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1636) ~[purpur-1.21.jar:1.21-2256-de2e7a7]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1337) ~[purpur-1.21.jar:1.21-2256-de2e7a7]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:332) ~[purpur-1.21.jar:1.21-2256-de2e7a7]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoSuchFieldError: Class org.bukkit.Tag does not have member field 'org.bukkit.Tag ITEMS_MUSIC_DISCS' [in thread "Server thread"]
        at worldguard-bukkit-7.0.10-dist.jar/com.sk89q.worldguard.bukkit.util.Materials.<clinit>(Materials.java:867) ~[worldguard-bukkit-7.0.10-dist.jar:?]
        at worldguard-bukkit-7.0.10-dist.jar/com.sk89q.worldguard.bukkit.listener.RegionProtectionListener.lambda$onUseBlock$2(RegionProtectionListener.java:256) ~[worldguard-bukkit-7.0.10-dist.jar:?]
        at com.google.common.base.Predicate.test(Predicate.java:79) ~[guava-32.1.2-jre.jar:?]
        at worldguard-bukkit-7.0.10-dist.jar/com.sk89q.worldguard.bukkit.event.block.AbstractBlockEvent.filterInternal(AbstractBlockEvent.java:132) ~[worldguard-bukkit-7.0.10-dist.jar:?]
        at worldguard-bukkit-7.0.10-dist.jar/com.sk89q.worldguard.bukkit.event.block.AbstractBlockEvent.filter(AbstractBlockEvent.java:124) ~[worldguard-bukkit-7.0.10-dist.jar:?]
        at worldguard-bukkit-7.0.10-dist.jar/com.sk89q.worldguard.bukkit.event.block.UseBlockEvent.filter(UseBlockEvent.java:39) ~[worldguard-bukkit-7.0.10-dist.jar:?]
        at worldguard-bukkit-7.0.10-dist.jar/com.sk89q.worldguard.bukkit.event.block.AbstractBlockEvent.filter(AbstractBlockEvent.java:160) ~[worldguard-bukkit-7.0.10-dist.jar:?]
        at worldguard-bukkit-7.0.10-dist.jar/com.sk89q.worldguard.bukkit.event.block.UseBlockEvent.filter(UseBlockEvent.java:39) ~[worldguard-bukkit-7.0.10-dist.jar:?]
        at worldguard-bukkit-7.0.10-dist.jar/com.sk89q.worldguard.bukkit.listener.RegionProtectionListener.onUseBlock(RegionProtectionListener.java:251) ~[worldguard-bukkit-7.0.10-dist.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor149.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:1.21-2256-de2e7a7]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.21.jar:1.21-2256-de2e7a7]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.21.jar:1.21-2256-de2e7a7]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at worldguard-bukkit-7.0.10-dist.jar/com.sk89q.worldguard.bukkit.util.Events.fireToCancel(Events.java:74) ~[worldguard-bukkit-7.0.10-dist.jar:?]
        at worldguard-bukkit-7.0.10-dist.jar/com.sk89q.worldguard.bukkit.listener.EventAbstractionListener.handleInventoryHolderUse(EventAbstractionListener.java:1215) ~[worldguard-bukkit-7.0.10-dist.jar:?]
        at worldguard-bukkit-7.0.10-dist.jar/com.sk89q.worldguard.bukkit.listener.EventAbstractionListener.onInventoryMoveItem(EventAbstractionListener.java:990) ~[worldguard-bukkit-7.0.10-dist.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor205.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:1.21-2256-de2e7a7]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.21.jar:1.21-2256-de2e7a7]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.21.jar:1.21-2256-de2e7a7]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.event.Event.callEvent(Event.java:45) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.world.level.block.entity.HopperBlockEntity.callPushMoveEvent(HopperBlockEntity.java:336) ~[purpur-1.21.jar:1.21-2256-de2e7a7]
        at net.minecraft.world.level.block.entity.HopperBlockEntity.hopperPush(HopperBlockEntity.java:261) ~[purpur-1.21.jar:1.21-2256-de2e7a7]
        at net.minecraft.world.level.block.entity.HopperBlockEntity.ejectItems(HopperBlockEntity.java:447) ~[purpur-1.21.jar:1.21-2256-de2e7a7]
        at net.minecraft.world.level.block.entity.HopperBlockEntity.tryMoveItems(HopperBlockEntity.java:205) ~[purpur-1.21.jar:1.21-2256-de2e7a7]
        at net.minecraft.world.level.block.entity.HopperBlockEntity.pushItemsTick(HopperBlockEntity.java:148) ~[purpur-1.21.jar:1.21-2256-de2e7a7]
        at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.tick(LevelChunk.java:995) ~[purpur-1.21.jar:1.21-2256-de2e7a7]
        at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.tick(LevelChunk.java:947) ~[purpur-1.21.jar:1.21-2256-de2e7a7]
        at net.minecraft.world.level.Level.tickBlockEntities(Level.java:1022) ~[purpur-1.21.jar:1.21-2256-de2e7a7]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:783) ~[purpur-1.21.jar:1.21-2256-de2e7a7]
        ... 6 more
````

### Optional WorldGuard-Report

https://paste.enginehub.org/TaePu6JY_.report

**Comment by aurorasmiles** [comment]
Don't lie in the template, use a plugin version that supports your Minecraft version

**Comment by DavidFrings** [comment]
Is it not for 1.21?

**Comment by DavidFrings** [comment]
Sorry
