### ISSUE TITLE
Could not pass various block events

### ISSUE THREAD

**Issue by Woolyenough** [EngineHub/WorldGuard#2113]
### WorldEdit Version

Bukkit-Official(7.3.4+6823-6263244)

### WorldGuard Version

Bukkit-Official(7.0.10+d9424b1)

### Platform Version

Paper 1.21 build 106

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of WorldGuard compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

When running WorldGuard on the latest version of Paper 1.21, it prints many errors to console. Here are two of the messages I've noticed being repeated referencing the two events `BlockSpreadEvent` & `BlockGrowEvent`:
```yaml
[10:14:30 ERROR]: Could not pass event BlockSpreadEvent to WorldGuard v7.0.10+d9424b1
java.lang.NoClassDefFoundError: Could not initialize class com.sk89q.worldguard.bukkit.util.Materials
        at worldguard-bukkit-7.0.10-dist.jar/com.sk89q.worldguard.bukkit.listener.WorldGuardBlockListener.onBlockSpread(WorldGuardBlockListener.java:552) ~[worldguard-bukkit-7.0.10-dist.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor426.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:84) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:1.21-106-3a47518]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.jar:1.21-106-3a47518]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.jar:1.21-106-3a47518]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.event.CraftEventFactory.handleBlockSpreadEvent(CraftEventFactory.java:963) ~[paper-1.21.jar:1.21-106-3a47518]
        at org.bukkit.craftbukkit.event.CraftEventFactory.handleBlockSpreadEvent(CraftEventFactory.java:947) ~[paper-1.21.jar:1.21-106-3a47518]
        at net.minecraft.world.level.block.GrowingPlantHeadBlock.randomTick(GrowingPlantHeadBlock.java:63) ~[paper-1.21.jar:1.21-106-3a47518]
        at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.randomTick(BlockBehaviour.java:1225) ~[paper-1.21.jar:1.21-106-3a47518]
        at net.minecraft.server.level.ServerLevel.optimiseRandomTick(ServerLevel.java:887) ~[paper-1.21.jar:1.21-106-3a47518]
        at net.minecraft.server.level.ServerLevel.tickChunk(ServerLevel.java:950) ~[paper-1.21.jar:1.21-106-3a47518]
        at net.minecraft.server.level.ServerChunkCache.tickChunks(ServerChunkCache.java:514) ~[paper-1.21.jar:1.21-106-3a47518]
        at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:407) ~[paper-1.21.jar:1.21-106-3a47518]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:732) ~[paper-1.21.jar:1.21-106-3a47518]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1805) ~[paper-1.21.jar:1.21-106-3a47518]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:473) ~[paper-1.21.jar:1.21-106-3a47518]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1597) ~[paper-1.21.jar:1.21-106-3a47518]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1303) ~[paper-1.21.jar:1.21-106-3a47518]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.jar:1.21-106-3a47518]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoSuchFieldError: Class org.bukkit.Tag does not have member field 'org.bukkit.Tag ITEMS_MUSIC_DISCS' [in thread "Server thread"]
        at worldguard-bukkit-7.0.10-dist.jar/com.sk89q.worldguard.bukkit.util.Materials.<clinit>(Materials.java:867) ~[worldguard-bukkit-7.0.10-dist.jar:?]
        ... 23 more
```
and
```yaml
[10:14:32 ERROR]: Could not pass event BlockGrowEvent to WorldGuard v7.0.10+d9424b1
java.lang.NoClassDefFoundError: Could not initialize class com.sk89q.worldguard.bukkit.util.Materials
        at worldguard-bukkit-7.0.10-dist.jar/com.sk89q.worldguard.bukkit.listener.WorldGuardBlockListener.handleGrow(WorldGuardBlockListener.java:641) ~[worldguard-bukkit-7.0.10-dist.jar:?]
        at worldguard-bukkit-7.0.10-dist.jar/com.sk89q.worldguard.bukkit.listener.WorldGuardBlockListener.onBlockGrow(WorldGuardBlockListener.java:636) ~[worldguard-bukkit-7.0.10-dist.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor419.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:84) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:1.21-106-3a47518]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.jar:1.21-106-3a47518]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.jar:1.21-106-3a47518]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.event.CraftEventFactory.handleBlockGrowEvent(CraftEventFactory.java:1321) ~[paper-1.21.jar:1.21-106-3a47518]
        at net.minecraft.world.level.block.VineBlock.randomTick(VineBlock.java:234) ~[paper-1.21.jar:1.21-106-3a47518]
        at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.randomTick(BlockBehaviour.java:1225) ~[paper-1.21.jar:1.21-106-3a47518]
        at net.minecraft.server.level.ServerLevel.optimiseRandomTick(ServerLevel.java:887) ~[paper-1.21.jar:1.21-106-3a47518]
        at net.minecraft.server.level.ServerLevel.tickChunk(ServerLevel.java:950) ~[paper-1.21.jar:1.21-106-3a47518]
        at net.minecraft.server.level.ServerChunkCache.tickChunks(ServerChunkCache.java:514) ~[paper-1.21.jar:1.21-106-3a47518]
        at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:407) ~[paper-1.21.jar:1.21-106-3a47518]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:732) ~[paper-1.21.jar:1.21-106-3a47518]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1805) ~[paper-1.21.jar:1.21-106-3a47518]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:473) ~[paper-1.21.jar:1.21-106-3a47518]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1597) ~[paper-1.21.jar:1.21-106-3a47518]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1303) ~[paper-1.21.jar:1.21-106-3a47518]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.jar:1.21-106-3a47518]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoSuchFieldError: Class org.bukkit.Tag does not have member field 'org.bukkit.Tag ITEMS_MUSIC_DISCS' [in thread "Server thread"]
        at worldguard-bukkit-7.0.10-dist.jar/com.sk89q.worldguard.bukkit.util.Materials.<clinit>(Materials.java:867) ~[worldguard-bukkit-7.0.10-dist.jar:?]
        at worldguard-bukkit-7.0.10-dist.jar/com.sk89q.worldguard.bukkit.listener.WorldGuardBlockListener.onBlockSpread(WorldGuardBlockListener.java:552) ~[worldguard-bukkit-7.0.10-dist.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor426.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:84) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:1.21-106-3a47518]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.jar:1.21-106-3a47518]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.jar:1.21-106-3a47518]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.event.CraftEventFactory.handleBlockSpreadEvent(CraftEventFactory.java:963) ~[paper-1.21.jar:1.21-106-3a47518]
        at org.bukkit.craftbukkit.event.CraftEventFactory.handleBlockSpreadEvent(CraftEventFactory.java:947) ~[paper-1.21.jar:1.21-106-3a47518]
        at net.minecraft.world.level.block.GrowingPlantHeadBlock.randomTick(GrowingPlantHeadBlock.java:63) ~[paper-1.21.jar:1.21-106-3a47518]
        ... 12 more```

### Expected Behavior

No errors.

### Reproduction Steps

1. Run the server with the latest WorldGuard and WorldEdit versions from the official Bukkit plugin page
2. Join the server
3. Observe the console errors

### Optional WorldGuard-Report

_No response_

### Anything Else?

_No response_

**Comment by me4502** [comment]
>  I am using a version of WorldGuard compatible with my Minecraft version.

you're not using a version of WG compatible with your MC version, they're all labelled as to what they support.

**Comment by Woolyenough** [comment]
I downloaded the latest version (listed as 1.21) on the plugin's Bukkit page; I am running the lastest Paper build for 1.21. Would it be possible for you to elaborate on your point?
