### ISSUE TITLE
Massive errors when logging into the server

### ISSUE THREAD

**Issue by hapugov** [EngineHub/WorldGuard#2121]
### WorldEdit Version

WorldEdit-Bukkit-Official(7.3.5+6880-8ba3d89)

### WorldGuard Version

 WorldGuard-Bukkit-Official (7.0.10+d9424b1)

### Platform Version

Paper version 1.21-124-master@df3b654

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of WorldGuard compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Hello, I’m currently assembling a new version of the server, initially I assembled it on purpur, then I went to test it on paper, installing only 2 plugins: WG, the second WE
And I get more lines with errors in the log
Licensed launcher without mods, client version 1.21
Operating system 
`windows 10 21h2 (os build 19044.2130)`

java version 
```
java 21.0.2 2024-01-16 LTS
Java(TM) SE Runtime Environment (build 21.0.2+13-LTS-58)
Java HotSpot(TM) 64-Bit Server VM (build 21.0.2+13-LTS-58, mixed mode, sharing)
```

Logs bellow
```
[19:31:53] [ServerMain/INFO]: [bootstrap] Running Java 21 (Java HotSpot(TM) 64-Bit Server VM 21.0.2+13-LTS-58; Oracle Corporation null) on Windows 10 10.0 (amd64)
[19:31:53] [ServerMain/INFO]: [bootstrap] Loading Paper 1.21-124-master@df3b654 (2024-08-02T00:02:38Z) for Minecraft 1.21
[19:31:54] [ServerMain/INFO]: [PluginInitializerManager] Initializing plugins...
[19:31:55] [ServerMain/INFO]: [PluginInitializerManager] Initialized 2 plugins
[19:31:55] [ServerMain/INFO]: [PluginInitializerManager] Bukkit plugins (2):
 - WorldEdit (7.3.5+6880-8ba3d89), WorldGuard (7.0.10+d9424b1)
[19:31:58] [ServerMain/INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[19:32:00] [ServerMain/INFO]: Loaded 1290 recipes
[19:32:00] [ServerMain/INFO]: Loaded 1399 advancements
[19:32:00] [Server thread/INFO]: Starting minecraft server version 1.21
[19:32:00] [Server thread/INFO]: Loading properties
[19:32:00] [Server thread/INFO]: This server is running Paper version 1.21-124-master@df3b654 (2024-08-02T00:02:38Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
[19:32:01] [Server thread/INFO]: [spark] This server bundles the spark profiler. For more information please visit https://docs.papermc.io/paper/profiling
[19:32:01] [Server thread/INFO]: Server Ping Player Sample Count: 12
[19:32:01] [Server thread/INFO]: Using 4 threads for Netty based IO
[19:32:02] [Server thread/INFO]: [ChunkTaskScheduler] Chunk system is using 1 I/O threads, 4 worker threads, and population gen parallelism of 4 threads
[19:32:02] [Server thread/INFO]: Default game type: SURVIVAL
[19:32:02] [Server thread/INFO]: Generating keypair
[19:32:02] [Server thread/INFO]: Starting Minecraft server on *:25565
[19:32:02] [Server thread/INFO]: Using default channel type
[19:32:02] [Server thread/INFO]: Paper: Using Java compression from Velocity.
[19:32:02] [Server thread/INFO]: Paper: Using Java cipher from Velocity.
[19:32:02] [Server thread/INFO]: [WorldEdit] Loading server plugin WorldEdit v7.3.5+6880-8ba3d89
[19:32:04] [Server thread/INFO]: Got request to register class com.sk89q.worldedit.bukkit.BukkitServerInterface with WorldEdit [com.sk89q.worldedit.extension.platform.PlatformManager@50047ac4]
[19:32:04] [Server thread/INFO]: [WorldGuard] Loading server plugin WorldGuard v7.0.10+d9424b1
[19:32:04] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[19:32:04] [Server thread/INFO]: [WorldEdit] Enabling WorldEdit v7.3.5+6880-8ba3d89
[19:32:04] [Server thread/INFO]: Registering commands with com.sk89q.worldedit.bukkit.BukkitServerInterface
[19:32:04] [Server thread/INFO]: WEPIF: Using the Bukkit Permissions API.
[19:32:04] [Server thread/INFO]: Using com.sk89q.worldedit.bukkit.adapter.impl.v1_21.PaperweightAdapter as the Bukkit adapter
[19:32:06] [Server thread/INFO]: Preparing level "world"
[19:32:07] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[19:32:07] [Server thread/INFO]: Time elapsed: 847 ms
[19:32:07] [Server thread/INFO]: Preparing start region for dimension minecraft:the_nether
[19:32:07] [Server thread/INFO]: Time elapsed: 61 ms
[19:32:07] [Server thread/INFO]: Preparing start region for dimension minecraft:the_end
[19:32:08] [Server thread/INFO]: Time elapsed: 42 ms
[19:32:08] [Server thread/INFO]: [WorldGuard] Enabling WorldGuard v7.0.10+d9424b1
[19:32:08] [Server thread/INFO]: [WorldGuard] (world) TNT ignition is PERMITTED.
[19:32:08] [Server thread/INFO]: [WorldGuard] (world) Lighters are PERMITTED.
[19:32:08] [Server thread/INFO]: [WorldGuard] (world) Lava fire is PERMITTED.
[19:32:08] [Server thread/INFO]: [WorldGuard] (world) Fire spread is UNRESTRICTED.
[19:32:08] [Server thread/INFO]: [WorldGuard] Loaded configuration for world 'world'
[19:32:08] [Server thread/INFO]: [WorldGuard] (world_nether) TNT ignition is PERMITTED.
[19:32:08] [Server thread/INFO]: [WorldGuard] (world_nether) Lighters are PERMITTED.
[19:32:08] [Server thread/INFO]: [WorldGuard] (world_nether) Lava fire is PERMITTED.
[19:32:08] [Server thread/INFO]: [WorldGuard] (world_nether) Fire spread is UNRESTRICTED.
[19:32:08] [Server thread/INFO]: [WorldGuard] Loaded configuration for world 'world_nether'
[19:32:08] [Server thread/INFO]: [WorldGuard] (world_the_end) TNT ignition is PERMITTED.
[19:32:08] [Server thread/INFO]: [WorldGuard] (world_the_end) Lighters are PERMITTED.
[19:32:08] [Server thread/INFO]: [WorldGuard] (world_the_end) Lava fire is PERMITTED.
[19:32:08] [Server thread/INFO]: [WorldGuard] (world_the_end) Fire spread is UNRESTRICTED.
[19:32:08] [Server thread/INFO]: [WorldGuard] Loaded configuration for world 'world_the_end'
[19:32:08] [Server thread/INFO]: [WorldGuard] Loading region data...
[19:32:08] [Server thread/INFO]: [spark] Starting background profiler...
[19:32:08] [Server thread/INFO]: [spark] The async-profiler engine is not supported for your os/arch (windows10/amd64), so the built-in Java engine will be used instead.
[19:32:09] [Server thread/INFO]: Done preparing level "world" (2.982s)
[19:32:09] [Server thread/INFO]: Running delayed init tasks
[19:32:09] [Server thread/INFO]: Done (16.104s)! For help, type "help"
[19:32:09] [Server thread/INFO]: Timings Reset
[19:32:26] [User Authenticator #0/INFO]: UUID of player hapug is 07ed2d73-ef57-4969-88c3-ad1b52da862e
[19:32:27] [Server thread/INFO]: hapug joined the game
[19:32:27] [Server thread/INFO]: hapug[/127.0.0.1:63307] logged in with entity id 26 at ([world]10.654299875296006, 82.0, 27.71412646367538)
[19:32:31] [Server thread/ERROR]: Could not pass event BlockFromToEvent to WorldGuard v7.0.10+d9424b1
java.lang.NoSuchFieldError: Class org.bukkit.Tag does not have member field 'org.bukkit.Tag ITEMS_MUSIC_DISCS'
	at worldguard-bukkit-7.0.10-dist.jar/com.sk89q.worldguard.bukkit.util.Materials.<clinit>(Materials.java:867) ~[worldguard-bukkit-7.0.10-dist.jar:?]
	at worldguard-bukkit-7.0.10-dist.jar/com.sk89q.worldguard.bukkit.listener.WorldGuardBlockListener.onBlockFromTo(WorldGuardBlockListener.java:114) ~[worldguard-bukkit-7.0.10-dist.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor22.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:1.21-124-df3b654]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.jar:1.21-124-df3b654]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.jar:1.21-124-df3b654]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.world.level.material.FlowingFluid.spreadToSides(FlowingFluid.java:186) ~[paper-1.21.jar:1.21-124-df3b654]
	at net.minecraft.world.level.material.FlowingFluid.spread(FlowingFluid.java:157) ~[paper-1.21.jar:1.21-124-df3b654]
	at net.minecraft.world.level.material.FlowingFluid.tick(FlowingFluid.java:502) ~[paper-1.21.jar:1.21-124-df3b654]
	at net.minecraft.world.level.material.FluidState.tick(FluidState.java:78) ~[paper-1.21.jar:1.21-124-df3b654]
	at net.minecraft.world.level.chunk.LevelChunk.postProcessGeneration(LevelChunk.java:808) ~[paper-1.21.jar:1.21-124-df3b654]
	at ca.spottedleaf.moonrise.patches.chunk_system.player.RegionizedPlayerChunkLoader$PlayerChunkLoaderData.updateQueues(RegionizedPlayerChunkLoader.java:828) ~[paper-1.21.jar:1.21-124-df3b654]
	at ca.spottedleaf.moonrise.patches.chunk_system.player.RegionizedPlayerChunkLoader.tick(RegionizedPlayerChunkLoader.java:311) ~[paper-1.21.jar:1.21-124-df3b654]
	at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:407) ~[paper-1.21.jar:1.21-124-df3b654]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:689) ~[paper-1.21.jar:1.21-124-df3b654]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1806) ~[paper-1.21.jar:1.21-124-df3b654]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:473) ~[paper-1.21.jar:1.21-124-df3b654]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1598) ~[paper-1.21.jar:1.21-124-df3b654]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1304) ~[paper-1.21.jar:1.21-124-df3b654]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.jar:1.21-124-df3b654]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[19:32:31] [Server thread/ERROR]: Could not pass event BlockFromToEvent to WorldGuard v7.0.10+d9424b1
java.lang.NoClassDefFoundError: Could not initialize class com.sk89q.worldguard.bukkit.util.Materials
	at worldguard-bukkit-7.0.10-dist.jar/com.sk89q.worldguard.bukkit.listener.WorldGuardBlockListener.onBlockFromTo(WorldGuardBlockListener.java:114) ~[worldguard-bukkit-7.0.10-dist.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor22.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:1.21-124-df3b654]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.jar:1.21-124-df3b654]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.jar:1.21-124-df3b654]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.world.level.material.FlowingFluid.spreadToSides(FlowingFluid.java:186) ~[paper-1.21.jar:1.21-124-df3b654]
	at net.minecraft.world.level.material.FlowingFluid.spread(FlowingFluid.java:157) ~[paper-1.21.jar:1.21-124-df3b654]
	at net.minecraft.world.level.material.FlowingFluid.tick(FlowingFluid.java:502) ~[paper-1.21.jar:1.21-124-df3b654]
	at net.minecraft.world.level.material.FluidState.tick(FluidState.java:78) ~[paper-1.21.jar:1.21-124-df3b654]
	at net.minecraft.world.level.chunk.LevelChunk.postProcessGeneration(LevelChunk.java:808) ~[paper-1.21.jar:1.21-124-df3b654]
	at ca.spottedleaf.moonrise.patches.chunk_system.player.RegionizedPlayerChunkLoader$PlayerChunkLoaderData.updateQueues(RegionizedPlayerChunkLoader.java:828) ~[paper-1.21.jar:1.21-124-df3b654]
	at ca.spottedleaf.moonrise.patches.chunk_system.player.RegionizedPlayerChunkLoader.tick(RegionizedPlayerChunkLoader.java:311) ~[paper-1.21.jar:1.21-124-df3b654]
	at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:407) ~[paper-1.21.jar:1.21-124-df3b654]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:689) ~[paper-1.21.jar:1.21-124-df3b654]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1806) ~[paper-1.21.jar:1.21-124-df3b654]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:473) ~[paper-1.21.jar:1.21-124-df3b654]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1598) ~[paper-1.21.jar:1.21-124-df3b654]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1304) ~[paper-1.21.jar:1.21-124-df3b654]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.jar:1.21-124-df3b654]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoSuchFieldError: Class org.bukkit.Tag does not have member field 'org.bukkit.Tag ITEMS_MUSIC_DISCS' [in thread "Server thread"]
	at worldguard-bukkit-7.0.10-dist.jar/com.sk89q.worldguard.bukkit.util.Materials.<clinit>(Materials.java:867) ~[worldguard-bukkit-7.0.10-dist.jar:?]
	... 23 more
[19:32:32] [Server thread/ERROR]: Could not pass event BlockFromToEvent to WorldGuard v7.0.10+d9424b1
java.lang.NoClassDefFoundError: Could not initialize class com.sk89q.worldguard.bukkit.util.Materials
	at worldguard-bukkit-7.0.10-dist.jar/com.sk89q.worldguard.bukkit.listener.WorldGuardBlockListener.onBlockFromTo(WorldGuardBlockListener.java:114) ~[worldguard-bukkit-7.0.10-dist.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor22.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:1.21-124-df3b654]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.jar:1.21-124-df3b654]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.jar:1.21-124-df3b654]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.world.level.material.FlowingFluid.spreadToSides(FlowingFluid.java:186) ~[paper-1.21.jar:1.21-124-df3b654]
	at net.minecraft.world.level.material.FlowingFluid.spread(FlowingFluid.java:157) ~[paper-1.21.jar:1.21-124-df3b654]
	at net.minecraft.world.level.material.FlowingFluid.tick(FlowingFluid.java:502) ~[paper-1.21.jar:1.21-124-df3b654]
	at net.minecraft.world.level.material.FluidState.tick(FluidState.java:78) ~[paper-1.21.jar:1.21-124-df3b654]
	at net.minecraft.world.level.chunk.LevelChunk.postProcessGeneration(LevelChunk.java:808) ~[paper-1.21.jar:1.21-124-df3b654]
	at ca.spottedleaf.moonrise.patches.chunk_system.player.RegionizedPlayerChunkLoader$PlayerChunkLoaderData.updateQueues(RegionizedPlayerChunkLoader.java:828) ~[paper-1.21.jar:1.21-124-df3b654]
	at ca.spottedleaf.moonrise.patches.chunk_system.player.RegionizedPlayerChunkLoader.tick(RegionizedPlayerChunkLoader.java:311) ~[paper-1.21.jar:1.21-124-df3b654]
	at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:407) ~[paper-1.21.jar:1.21-124-df3b654]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:689) ~[paper-1.21.jar:1.21-124-df3b654]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1806) ~[paper-1.21.jar:1.21-124-df3b654]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:473) ~[paper-1.21.jar:1.21-124-df3b654]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1598) ~[paper-1.21.jar:1.21-124-df3b654]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1304) ~[paper-1.21.jar:1.21-124-df3b654]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.jar:1.21-124-df3b654]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoSuchFieldError: Class org.bukkit.Tag does not have member field 'org.bukkit.Tag ITEMS_MUSIC_DISCS' [in thread "Server thread"]
	at worldguard-bukkit-7.0.10-dist.jar/com.sk89q.worldguard.bukkit.util.Materials.<clinit>(Materials.java:867) ~[worldguard-bukkit-7.0.10-dist.jar:?]
	... 23 more
[19:32:32] [Server thread/ERROR]: Could not pass event BlockFromToEvent to WorldGuard v7.0.10+d9424b1
java.lang.NoClassDefFoundError: Could not initialize class com.sk89q.worldguard.bukkit.util.Materials
	at worldguard-bukkit-7.0.10-dist.jar/com.sk89q.worldguard.bukkit.listener.WorldGuardBlockListener.onBlockFromTo(WorldGuardBlockListener.java:114) ~[worldguard-bukkit-7.0.10-dist.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor22.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:1.21-124-df3b654]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.jar:1.21-124-df3b654]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.jar:1.21-124-df3b654]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.world.level.material.FlowingFluid.spreadToSides(FlowingFluid.java:186) ~[paper-1.21.jar:1.21-124-df3b654]
	at net.minecraft.world.level.material.FlowingFluid.spread(FlowingFluid.java:157) ~[paper-1.21.jar:1.21-124-df3b654]
	at net.minecraft.world.level.material.FlowingFluid.tick(FlowingFluid.java:502) ~[paper-1.21.jar:1.21-124-df3b654]
	at net.minecraft.world.level.material.FluidState.tick(FluidState.java:78) ~[paper-1.21.jar:1.21-124-df3b654]
	at net.minecraft.world.level.chunk.LevelChunk.postProcessGeneration(LevelChunk.java:808) ~[paper-1.21.jar:1.21-124-df3b654]
	at ca.spottedleaf.moonrise.patches.chunk_system.player.RegionizedPlayerChunkLoader$PlayerChunkLoaderData.updateQueues(RegionizedPlayerChunkLoader.java:828) ~[paper-1.21.jar:1.21-124-df3b654]
	at ca.spottedleaf.moonrise.patches.chunk_system.player.RegionizedPlayerChunkLoader.tick(RegionizedPlayerChunkLoader.java:311) ~[paper-1.21.jar:1.21-124-df3b654]
	at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:407) ~[paper-1.21.jar:1.21-124-df3b654]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:689) ~[paper-1.21.jar:1.21-124-df3b654]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1806) ~[paper-1.21.jar:1.21-124-df3b654]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:473) ~[paper-1.21.jar:1.21-124-df3b654]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1598) ~[paper-1.21.jar:1.21-124-df3b654]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1304) ~[paper-1.21.jar:1.21-124-df3b654]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.jar:1.21-124-df3b654]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoSuchFieldError: Class org.bukkit.Tag does not have member field 'org.bukkit.Tag ITEMS_MUSIC_DISCS' [in thread "Server thread"]
	at worldguard-bukkit-7.0.10-dist.jar/com.sk89q.worldguard.bukkit.util.Materials.<clinit>(Materials.java:867) ~[worldguard-bukkit-7.0.10-dist.jar:?]
	... 23 more
```

### Expected Behavior

Absence of a bunch of errors in the log

### Reproduction Steps

1. Download paper
2. Download WE
3. Download WG
4. Place WG and WE into plugins folder
5. Start server
6. Join server
7. Take an error

**Comment by aurorasmiles** [comment]
Use a version that supports 1.21 when using 1.21

**Comment by hapugov** [comment]
I downloaded the version from [here](https://modrinth.com/plugin/worldedit/version/Jo76t1oi), support for version 1.21 has stopped
Are you saying that the problem is not in WG but in WE?

**Comment by aurorasmiles** [comment]
You linked WorldEdit, not WorldGuard. You need to update WorldGuard.
