### ISSUE TITLE
spam error in console

### ISSUE THREAD

**Issue by M1WaNA** [EngineHub/WorldGuard#2127]
### WorldEdit Version

WORLDEDIT-BUKKIT-7.3.5.JAR

### WorldGuard Version

WORLDGUARD-BUKKIT-7.0.10-DIST.JAR

### Platform Version

spigot-1.21-R0.1-SNAPSHOT

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of WorldGuard compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

WorldGuard is spamming errors in the console, and I don't know what it's related to since there are only 2 protected areas on the server

### Expected Behavior

The console did not scroll up.

### Reproduction Steps

The player joins the server, and that's it.

### Optional WorldGuard-Report

https://paste.enginehub.org/bvMr9GX6W.report

### Anything Else?

at net.minecraft.server.level.ChunkProviderServer.t(ChunkProviderServer.java:415) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4204-Spigot-146439e-a1d2cd1]at net.minecraft.server.level.ChunkProviderServer.a(ChunkProviderServer.java:352) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4204-Spigot-146439e-a1d2cd1]at net.minecraft.server.level.WorldServer.a(WorldServer.java:412) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4204-Spigot-146439e-a1d2cd1]... 6 more[18:17:17] [Server thread/ERROR]: Could not pass event BlockFromToEvent to WorldGuard v7.0.10+d9424b1org.bukkit.event.EventException: nullat org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:601) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:588) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]at net.minecraft.world.level.material.FluidTypeFlowing.a(FluidTypeFlowing.java:186) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4204-Spigot-146439e-a1d2cd1]at net.minecraft.world.level.material.FluidTypeFlowing.a(FluidTypeFlowing.java:158) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4204-Spigot-146439e-a1d2cd1]at net.minecraft.world.level.m

**Comment by Joo200** [comment]
WG 7.0.10 doesn't support 1.21, use 7.0.11-beta1
