### ISSUE TITLE
Error on paper 1.21.1

### ISSUE THREAD

**Issue by MassiveLag** [EngineHub/WorldGuard#2133]
### WorldEdit Version

FastAsyncWorldEdit-889

### WorldGuard Version

7.0.10

### Platform Version

Paper Latest

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of WorldGuard compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

it throws errors when interacting:

`
WorldGuard throws this error on 1.21.1[22:14:41 ERROR]: Could not pass event PlayerInteractEvent to WorldGuard v7.0.10+d9424b1
java.lang.NoClassDefFoundError: Could not initialize class com.sk89q.worldguard.bukkit.util.Materials
        at worldguard-bukkit-7.0.10-dist (4).jar/com.sk89q.worldguard.bukkit.listener.WorldGuardPlayerListener.handleBlockRightClick(WorldGuardPlayerListener.java:248) ~[worldguard-bukkit-7.0.10-dist (4).jar:?]
        at worldguard-bukkit-7.0.10-dist (4).jar/com.sk89q.worldguard.bukkit.listener.WorldGuardPlayerListener.onPlayerInteract(WorldGuardPlayerListener.java:210) ~[worldguard-bukkit-7.0.10-dist (4).jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor143.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[axolotl-api-1.21.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[axolotl-api-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-DEV-cfaf3dd]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[axolotl-api-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:57) ~[axolotl-1.21.1.jar:1.21.1-DEV-cfaf3dd]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[axolotl-1.21.1.jar:1.21.1-DEV-cfaf3dd]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630) ~[axolotl-api-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:606) ~[axolotl-1.21.1.jar:1.21.1-DEV-cfaf3dd]
        at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:548) ~[axolotl-1.21.1.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1943) ~[axolotl-1.21.1.jar:1.21.1-DEV-cfaf3dd]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:44) ~[axolotl-1.21.1.jar:1.21.1-DEV-cfaf3dd]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:11) ~[axolotl-1.21.1.jar:1.21.1-DEV-cfaf3dd]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[axolotl-1.21.1.jar:1.21.1-DEV-cfaf3dd]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[axolotl-1.21.1.jar:1.21.1-DEV-cfaf3dd]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[axolotl-1.21.1.jar:1.21.1-DEV-cfaf3dd]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[axolotl-1.21.1.jar:1.21.1-DEV-cfaf3dd]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1559) ~[axolotl-1.21.1.jar:1.21.1-DEV-cfaf3dd]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:203) ~[axolotl-1.21.1.jar:1.21.1-DEV-cfaf3dd]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[axolotl-1.21.1.jar:1.21.1-DEV-cfaf3dd]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1536) ~[axolotl-1.21.1.jar:1.21.1-DEV-cfaf3dd]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1529) ~[axolotl-1.21.1.jar:1.21.1-DEV-cfaf3dd]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[axolotl-1.21.1.jar:1.21.1-DEV-cfaf3dd]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1488) ~[axolotl-1.21.1.jar:1.21.1-DEV-cfaf3dd]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1495) ~[axolotl-1.21.1.jar:1.21.1-DEV-cfaf3dd]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1340) ~[axolotl-1.21.1.jar:1.21.1-DEV-cfaf3dd]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:334) ~[axolotl-1.21.1.jar:1.21.1-DEV-cfaf3dd]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoSuchFieldError: Class org.bukkit.Tag does not have member field 'org.bukkit.Tag ITEMS_MUSIC_DISCS' [in thread "Server thread"]
        at worldguard-bukkit-7.0.10-dist (4).jar/com.sk89q.worldguard.bukkit.util.Materials.<clinit>(Materials.java:867) ~[worldguard-bukkit-7.0.10-dist (4).jar:?]
        at worldguard-bukkit-7.0.10-dist (4).jar/com.sk89q.worldguard.bukkit.listener.EventAbstractionListener.isBlockModifiedOnClick(EventAbstractionListener.java:1242) ~[worldguard-bukkit-7.0.10-dist (4).jar:?]
        at worldguard-bukkit-7.0.10-dist (4).jar/com.sk89q.worldguard.bukkit.listener.EventAbstractionListener.onPlayerInteract(EventAbstractionListener.java:507) ~[worldguard-bukkit-7.0.10-dist (4).jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor249.execute(Unknown Source) ~[?:?]
        ... 26 more`

### Expected Behavior

No errors

### Reproduction Steps

1. Right or left clicking any blocks.
2. Throws errors on console.

### Optional WorldGuard-Report

https://paste.enginehub.org/WnvpE58P0.report

### Anything Else?

No

**Comment by aurorasmiles** [comment]
Don't lie in the template
Update
