### ISSUE TITLE
Console flooded with errors

### ISSUE THREAD

**Issue by neomoth** [EngineHub/WorldGuard#2145]
### WorldEdit Version

Bukkit-Official(7.3.6+6892-3d660b8)

### WorldGuard Version

Bukkit-Official (7.0.10+d9424b1)

### Platform Version

Paper-1.21.1-77

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEdit compatible with my Minecraft version.
- [X] I am using a version of WorldGuard compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.
- [X] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [X] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

Getting console spam with errors on block updates and other events that worldedit tracks to pass to world guard.
Example snippet:
```
[07:03:37 ERROR]: Could not pass event BlockGrowEvent to WorldGuard v7.0.10+d9424b1
java.lang.NoClassDefFoundError: Could not initialize class com.sk89q.worldguard.bukkit.util.Materials
        at worldguard-bukkit-7.0.10-dist.jar/com.sk89q.worldguard.bukkit.listener.WorldGuardBlockListener.handleGrow(WorldGuardBlockListener.java:641) ~[worldguard-bukkit-7.0.10-dist.jar:?]
        at worldguard-bukkit-7.0.10-dist.jar/com.sk89q.worldguard.bukkit.listener.WorldGuardBlockListener.onBlockGrow(WorldGuardBlockListener.java:636) ~[worldguard-bukkit-7.0.10-dist.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor98.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-77-4ff58c4]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.1.jar:1.21.1-77-4ff58c4]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.1.jar:1.21.1-77-4ff58c4]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.event.CraftEventFactory.handleBlockGrowEvent(CraftEventFactory.java:1327) ~[paper-1.21.1.jar:1.21.1-77-4ff58c4]
        at net.minecraft.world.level.block.VineBlock.randomTick(VineBlock.java:234) ~[paper-1.21.1.jar:1.21.1-77-4ff58c4]
        at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.randomTick(BlockBehaviour.java:1226) ~[paper-1.21.1.jar:1.21.1-77-4ff58c4]
        at net.minecraft.server.level.ServerLevel.optimiseRandomTick(ServerLevel.java:844) ~[paper-1.21.1.jar:1.21.1-77-4ff58c4]
        at net.minecraft.server.level.ServerLevel.tickChunk(ServerLevel.java:907) ~[paper-1.21.1.jar:1.21.1-77-4ff58c4]
        at net.minecraft.server.level.ServerChunkCache.tickChunks(ServerChunkCache.java:515) ~[paper-1.21.1.jar:1.21.1-77-4ff58c4]
        at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:408) ~[paper-1.21.1.jar:1.21.1-77-4ff58c4]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:689) ~[paper-1.21.1.jar:1.21.1-77-4ff58c4]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1806) ~[paper-1.21.1.jar:1.21.1-77-4ff58c4]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:473) ~[paper-1.21.1.jar:1.21.1-77-4ff58c4]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1598) ~[paper-1.21.1.jar:1.21.1-77-4ff58c4]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1304) ~[paper-1.21.1.jar:1.21.1-77-4ff58c4]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.1.jar:1.21.1-77-4ff58c4]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoSuchFieldError: Class org.bukkit.Tag does not have member field 'org.bukkit.Tag ITEMS_MUSIC_DISCS' [in thread "Server thread"]
        at worldguard-bukkit-7.0.10-dist.jar/com.sk89q.worldguard.bukkit.util.Materials.<clinit>(Materials.java:867) ~[worldguard-bukkit-7.0.10-dist.jar:?]
        ... 23 more
[07:03:37 ERROR]: Could not pass event BlockGrowEvent to WorldGuard v7.0.10+d9424b1
java.lang.NoClassDefFoundError: Could not initialize class com.sk89q.worldguard.bukkit.util.Materials
        at worldguard-bukkit-7.0.10-dist.jar/com.sk89q.worldguard.bukkit.listener.WorldGuardBlockListener.handleGrow(WorldGuardBlockListener.java:641) ~[worldguard-bukkit-7.0.10-dist.jar:?]
        at worldguard-bukkit-7.0.10-dist.jar/com.sk89q.worldguard.bukkit.listener.WorldGuardBlockListener.onBlockGrow(WorldGuardBlockListener.java:636) ~[worldguard-bukkit-7.0.10-dist.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor98.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-77-4ff58c4]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.1.jar:1.21.1-77-4ff58c4]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.1.jar:1.21.1-77-4ff58c4]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.event.CraftEventFactory.handleBlockGrowEvent(CraftEventFactory.java:1327) ~[paper-1.21.1.jar:1.21.1-77-4ff58c4]
        at net.minecraft.world.level.block.VineBlock.randomTick(VineBlock.java:234) ~[paper-1.21.1.jar:1.21.1-77-4ff58c4]
        at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.randomTick(BlockBehaviour.java:1226) ~[paper-1.21.1.jar:1.21.1-77-4ff58c4]
        at net.minecraft.server.level.ServerLevel.optimiseRandomTick(ServerLevel.java:844) ~[paper-1.21.1.jar:1.21.1-77-4ff58c4]
        at net.minecraft.server.level.ServerLevel.tickChunk(ServerLevel.java:907) ~[paper-1.21.1.jar:1.21.1-77-4ff58c4]
        at net.minecraft.server.level.ServerChunkCache.tickChunks(ServerChunkCache.java:515) ~[paper-1.21.1.jar:1.21.1-77-4ff58c4]
        at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:408) ~[paper-1.21.1.jar:1.21.1-77-4ff58c4]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:689) ~[paper-1.21.1.jar:1.21.1-77-4ff58c4]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1806) ~[paper-1.21.1.jar:1.21.1-77-4ff58c4]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:473) ~[paper-1.21.1.jar:1.21.1-77-4ff58c4]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1598) ~[paper-1.21.1.jar:1.21.1-77-4ff58c4]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1304) ~[paper-1.21.1.jar:1.21.1-77-4ff58c4]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.1.jar:1.21.1-77-4ff58c4]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoSuchFieldError: Class org.bukkit.Tag does not have member field 'org.bukkit.Tag ITEMS_MUSIC_DISCS' [in thread "Server thread"]
        at worldguard-bukkit-7.0.10-dist.jar/com.sk89q.worldguard.bukkit.util.Materials.<clinit>(Materials.java:867) ~[worldguard-bukkit-7.0.10-dist.jar:?]
        ... 23 more
[07:03:37 ERROR]: Could not pass event BlockGrowEvent to WorldGuard v7.0.10+d9424b1
java.lang.NoClassDefFoundError: Could not initialize class com.sk89q.worldguard.bukkit.util.Materials
        at worldguard-bukkit-7.0.10-dist.jar/com.sk89q.worldguard.bukkit.listener.WorldGuardBlockListener.handleGrow(WorldGuardBlockListener.java:641) ~[worldguard-bukkit-7.0.10-dist.jar:?]
        at worldguard-bukkit-7.0.10-dist.jar/com.sk89q.worldguard.bukkit.listener.WorldGuardBlockListener.onBlockGrow(WorldGuardBlockListener.java:636) ~[worldguard-bukkit-7.0.10-dist.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor98.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-77-4ff58c4]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.1.jar:1.21.1-77-4ff58c4]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.1.jar:1.21.1-77-4ff58c4]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.event.CraftEventFactory.handleBlockGrowEvent(CraftEventFactory.java:1327) ~[paper-1.21.1.jar:1.21.1-77-4ff58c4]
        at net.minecraft.world.level.block.VineBlock.randomTick(VineBlock.java:234) ~[paper-1.21.1.jar:1.21.1-77-4ff58c4]
        at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.randomTick(BlockBehaviour.java:1226) ~[paper-1.21.1.jar:1.21.1-77-4ff58c4]
        at net.minecraft.server.level.ServerLevel.optimiseRandomTick(ServerLevel.java:844) ~[paper-1.21.1.jar:1.21.1-77-4ff58c4]
        at net.minecraft.server.level.ServerLevel.tickChunk(ServerLevel.java:907) ~[paper-1.21.1.jar:1.21.1-77-4ff58c4]
        at net.minecraft.server.level.ServerChunkCache.tickChunks(ServerChunkCache.java:515) ~[paper-1.21.1.jar:1.21.1-77-4ff58c4]
        at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:408) ~[paper-1.21.1.jar:1.21.1-77-4ff58c4]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:689) ~[paper-1.21.1.jar:1.21.1-77-4ff58c4]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1806) ~[paper-1.21.1.jar:1.21.1-77-4ff58c4]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:473) ~[paper-1.21.1.jar:1.21.1-77-4ff58c4]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1598) ~[paper-1.21.1.jar:1.21.1-77-4ff58c4]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1304) ~[paper-1.21.1.jar:1.21.1-77-4ff58c4]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.1.jar:1.21.1-77-4ff58c4]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoSuchFieldError: Class org.bukkit.Tag does not have member field 'org.bukkit.Tag ITEMS_MUSIC_DISCS' [in thread "Server thread"]
        at worldguard-bukkit-7.0.10-dist.jar/com.sk89q.worldguard.bukkit.util.Materials.<clinit>(Materials.java:867) ~[worldguard-bukkit-7.0.10-dist.jar:?]
        ... 23 more
```
This is annoying for obvious reasons.

### Expected Behavior

Expected behavior is that these errors should not be occurring.

### Reproduction Steps

1. Initialize a papermc server on 1.21.1-77
2. Add worldguard and worldedit
3. Voila, console chaos.

### Optional WorldGuard-Report

https://paste.enginehub.org/XgjY2bd3z.report

### Anything Else?

I have seen several invalid reports claiming that there was a lie on the checklist. I would like to confirm that ***no, i am not using FAWE or AWE.*** I have tested with both and this bug persists across both of those worldedit forks as well as the main worldedit.
The jar is present in the plugin folder but is not being loaded as i've modified the extension to `.jar.old` and running worldedit commands shows the normal purple text from vanilla worldedit.

![image](https://github.com/user-attachments/assets/6f82ad7e-2580-467c-ae2a-6ea392b38398)

Everything on the checklist is true to the best of my knowledge and as such I ask that this issue is looked into further by the development team.

**Comment by me4502** [comment]
use a version of WG that's actually labelled to support your MC version.

**Comment by neomoth** [comment]
> use a version of WG that's actually labelled to support your MC version.

Apologies, did not notice the new version. I was given this issue by a friend and should have looked at the actual release page instead of assuming this was latest.
