### ISSUE TITLE
In 1.21 version set the "build-place: deny" but can place block

### ISSUE THREAD

**Issue by SmallXY** [EngineHub/WorldGuard#2166]
### WorldEdit Version

worldedit-bukkit-7.3.9

### WorldGuard Version

WorldGuard 7.0.13 beta 2 (MC 1.21.4) 1.11 MB	5 days ago	1.21	1,011 WorldGuard 7.0.13 beta 1 (MC 1.21.3) 1.11 MB	Nov 10, 2024	1.21	7,634 WorldGuard 7.0.12 (MC 1.21 - 1.21.1) 

### Platform Version

4248-Spigot-491f367-ae4f5a0 (MC: 1.21)

### Confirmations

- [ ] I am using the most recent Minecraft release.
- [x] I am using a version of WorldEdit compatible with my Minecraft version.
- [ ] I am using a version of WorldGuard compatible with my Minecraft version.
- [x] I am using the latest or recommended version of my platform software.
- [x] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [x] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

I have set up land claims to prevent placing and mining blocks, but I can place blocks while mining is prohibited.
[12:05:22] [Server thread/ERROR]: Could not pass event PlaceBlockEvent to WorldGuard v7.0.13-beta-2+5c4848b
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:601) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:588) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
        at com.sk89q.worldguard.bukkit.util.Events.fireToCancel(Events.java:74) ~[?:?]
        at com.sk89q.worldguard.bukkit.listener.EventAbstractionListener.onBlockIgnite(EventAbstractionListener.java:630) ~[?:?]
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
        at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:601) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:588) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_21_R1.event.CraftEventFactory.callBlockIgniteEvent(CraftEventFactory.java:1382) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4248-Spigot-491f367-ae4f5a0]
        at net.minecraft.world.level.material.FluidTypeLava.b(FluidTypeLava.java:89) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4248-Spigot-491f367-ae4f5a0]
        at net.minecraft.world.level.material.Fluid.b(SourceFile:91) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4248-Spigot-491f367-ae4f5a0]
        at net.minecraft.server.level.WorldServer.a(WorldServer.java:588) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4248-Spigot-491f367-ae4f5a0]
        at net.minecraft.server.level.ChunkProviderServer.t(ChunkProviderServer.java:415) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4248-Spigot-491f367-ae4f5a0]
        at net.minecraft.server.level.ChunkProviderServer.a(ChunkProviderServer.java:352) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4248-Spigot-491f367-ae4f5a0]
        at net.minecraft.server.level.WorldServer.a(WorldServer.java:412) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4248-Spigot-491f367-ae4f5a0]
        at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:1472) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4248-Spigot-491f367-ae4f5a0]
        at net.minecraft.server.dedicated.DedicatedServer.c(DedicatedServer.java:406) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4248-Spigot-491f367-ae4f5a0]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1321) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4248-Spigot-491f367-ae4f5a0]
        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1071) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4248-Spigot-491f367-ae4f5a0]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4248-Spigot-491f367-ae4f5a0]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.sk89q.worldguard.bukkit.util.Materials
        at com.sk89q.worldguard.bukkit.listener.RegionFlagsListener.onPlaceBlock(RegionFlagsListener.java:67) ~[?:?]
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
        at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
        ... 24 more
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.IllegalArgumentException: No enum constant org.bukkit.entity.EntityType.OAK_BOAT [in thread "Server thread"]
        at java.base/java.lang.Enum.valueOf(Enum.java:293) ~[?:?]
        at org.bukkit.entity.EntityType.valueOf(EntityType.java:26) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_21_R1.legacy.FieldRename.valueOf_EntityType(FieldRename.java:210) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4248-Spigot-491f367-ae4f5a0]
        at com.sk89q.worldguard.bukkit.util.Materials.BUKKIT_CUSTOM_METHOD_org_bukkit_craftbukkit_v1_21_R1_legacy_FieldRename_valueOf_EntityType(Materials.java) ~[?:?]
        at com.sk89q.worldguard.bukkit.util.Materials.<clinit>(Materials.java:86) ~[?:?]
        at com.sk89q.worldguard.bukkit.listener.WorldGuardBlockListener.onBlockSpread(WorldGuardBlockListener.java:553) ~[?:?]
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
        at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:601) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:588) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_21_R1.event.CraftEventFactory.handleBlockSpreadEvent(CraftEventFactory.java:894) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4248-Spigot-491f367-ae4f5a0]
        at net.minecraft.world.level.block.BlockVine.b(BlockVine.java:270) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4248-Spigot-491f367-ae4f5a0]
        at net.minecraft.world.level.block.state.BlockBase$BlockData.b(BlockBase.java:1090) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4248-Spigot-491f367-ae4f5a0]
        at net.minecraft.server.level.WorldServer.a(WorldServer.java:582) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4248-Spigot-491f367-ae4f5a0]
        ... 9 more
[12:05:22] [Server thread/ERROR]: Could not pass event PlaceBlockEvent to WorldGuard v7.0.13-beta-2+5c4848b
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:601) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:588) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
        at com.sk89q.worldguard.bukkit.util.Events.fireToCancel(Events.java:74) ~[?:?]
        at com.sk89q.worldguard.bukkit.listener.EventAbstractionListener.onBlockIgnite(EventAbstractionListener.java:630) ~[?:?]
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
        at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:601) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:588) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_21_R1.event.CraftEventFactory.callBlockIgniteEvent(CraftEventFactory.java:1382) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4248-Spigot-491f367-ae4f5a0]
        at net.minecraft.world.level.material.FluidTypeLava.b(FluidTypeLava.java:89) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4248-Spigot-491f367-ae4f5a0]
        at net.minecraft.world.level.material.Fluid.b(SourceFile:91) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4248-Spigot-491f367-ae4f5a0]
        at net.minecraft.server.level.WorldServer.a(WorldServer.java:588) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4248-Spigot-491f367-ae4f5a0]
        at net.minecraft.server.level.ChunkProviderServer.t(ChunkProviderServer.java:415) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4248-Spigot-491f367-ae4f5a0]
        at net.minecraft.server.level.ChunkProviderServer.a(ChunkProviderServer.java:352) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4248-Spigot-491f367-ae4f5a0]
        at net.minecraft.server.level.WorldServer.a(WorldServer.java:412) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4248-Spigot-491f367-ae4f5a0]
        at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:1472) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4248-Spigot-491f367-ae4f5a0]
        at net.minecraft.server.dedicated.DedicatedServer.c(DedicatedServer.java:406) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4248-Spigot-491f367-ae4f5a0]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1321) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4248-Spigot-491f367-ae4f5a0]
        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1071) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4248-Spigot-491f367-ae4f5a0]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4248-Spigot-491f367-ae4f5a0]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.sk89q.worldguard.bukkit.util.Materials
        at com.sk89q.worldguard.bukkit.listener.RegionProtectionListener.onPlaceBlock(RegionProtectionListener.java:166) ~[?:?]
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
        at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
        ... 24 more
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.IllegalArgumentException: No enum constant org.bukkit.entity.EntityType.OAK_BOAT [in thread "Server thread"]
        at java.base/java.lang.Enum.valueOf(Enum.java:293) ~[?:?]
        at org.bukkit.entity.EntityType.valueOf(EntityType.java:26) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_21_R1.legacy.FieldRename.valueOf_EntityType(FieldRename.java:210) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4248-Spigot-491f367-ae4f5a0]
        at com.sk89q.worldguard.bukkit.util.Materials.BUKKIT_CUSTOM_METHOD_org_bukkit_craftbukkit_v1_21_R1_legacy_FieldRename_valueOf_EntityType(Materials.java) ~[?:?]
        at com.sk89q.worldguard.bukkit.util.Materials.<clinit>(Materials.java:86) ~[?:?]
        at com.sk89q.worldguard.bukkit.listener.WorldGuardBlockListener.onBlockSpread(WorldGuardBlockListener.java:553) ~[?:?]
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
        at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:601) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:588) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_21_R1.event.CraftEventFactory.handleBlockSpreadEvent(CraftEventFactory.java:894) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4248-Spigot-491f367-ae4f5a0]
        at net.minecraft.world.level.block.BlockVine.b(BlockVine.java:270) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4248-Spigot-491f367-ae4f5a0]
        at net.minecraft.world.level.block.state.BlockBase$BlockData.b(BlockBase.java:1090) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4248-Spigot-491f367-ae4f5a0]
        at net.minecraft.server.level.WorldServer.a(WorldServer.java:582) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4248-Spigot-491f367-ae4f5a0]
        ... 9 more
>

### Expected Behavior

If I set both no place and no break, they should both take effect.

### Reproduction Steps

1. ...
2. ...

### Optional WorldGuard-Report

https://paste.enginehub.org/f6Cth4l-b.report

**Comment by me4502** [comment]
you need to use a WG version labelled to support your MC version. that error is due to spigot api breakages
