### ISSUE TITLE
Errors in console `Could not pass event PlaceBlockEvent to WorldGuard`

### ISSUE THREAD

**Issue by Stoupy51** [EngineHub/WorldGuard#2168]
### WorldEdit Version

Bukkit-Official (7.3.9+6959-7adf70b)

### WorldGuard Version

Bukkit-Official (7.0.12+829a4a4)

### Platform Version

Paper 1.21.4-66-d00344a

### Confirmations

- [x] I am using the most recent Minecraft release.
- [ ] I am using a version of WorldEdit compatible with my Minecraft version.
- [ ] I am using a version of WorldGuard compatible with my Minecraft version.
- [x] I am using the latest or recommended version of my platform software.
- [x] I am NOT using a hybrid server, e.g. a server that combines Bukkit and Forge. Examples include Arclight, Mohist, and Cardboard.
- [x] I am NOT using a fork of WorldEdit, such as FastAsyncWorldEdit (FAWE) or AsyncWorldEdit (AWE)

### Bug Description

[12:05:11 ERROR]: Could not pass event PlaceBlockEvent to WorldGuard v7.0.12+829a4a4
java.lang.NoSuchFieldError: Class org.bukkit.Tag does not have member field 'org.bukkit.Tag ITEMS_TRIM_TEMPLATES'
	at worldguard-bukkit-7.0.12-dist.jar/com.sk89q.worldguard.bukkit.util.Materials.<clinit>(Materials.java:913) ~[worldguard-bukkit-7.0.12-dist.jar:?]
	at worldguard-bukkit-7.0.12-dist.jar/com.sk89q.worldguard.bukkit.listener.RegionFlagsListener.onPlaceBlock(RegionFlagsListener.java:67) ~[worldguard-bukkit-7.0.12-dist.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.4.jar:1.21.4-66-d00344a]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.4.jar:1.21.4-66-d00344a]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
	at worldguard-bukkit-7.0.12-dist.jar/com.sk89q.worldguard.bukkit.util.Events.fireBulkEventToCancel(Events.java:112) ~[worldguard-bukkit-7.0.12-dist.jar:?]
	at worldguard-bukkit-7.0.12-dist.jar/com.sk89q.worldguard.bukkit.listener.EventAbstractionListener.onStructureGrowEvent(EventAbstractionListener.java:278) ~[worldguard-bukkit-7.0.12-dist.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.4.jar:1.21.4-66-d00344a]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.4.jar:1.21.4-66-d00344a]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.world.level.block.SaplingBlock.advanceTree(SaplingBlock.java:74) ~[paper-1.21.4.jar:1.21.4-66-d00344a]
	at net.minecraft.world.level.block.SaplingBlock.randomTick(SaplingBlock.java:50) ~[paper-1.21.4.jar:1.21.4-66-d00344a]
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.randomTick(BlockBehaviour.java:882) ~[paper-1.21.4.jar:1.21.4-66-d00344a]
	at net.minecraft.server.level.ServerLevel.optimiseRandomTick(ServerLevel.java:907) ~[paper-1.21.4.jar:1.21.4-66-d00344a]
	at net.minecraft.server.level.ServerLevel.tickChunk(ServerLevel.java:967) ~[paper-1.21.4.jar:1.21.4-66-d00344a]
	at net.minecraft.server.level.ServerChunkCache.tickChunks(ServerChunkCache.java:624) ~[paper-1.21.4.jar:1.21.4-66-d00344a]
	at net.minecraft.server.level.ServerChunkCache.tickChunks(ServerChunkCache.java:522) ~[paper-1.21.4.jar:1.21.4-66-d00344a]
	at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:494) ~[paper-1.21.4.jar:1.21.4-66-d00344a]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:776) ~[paper-1.21.4.jar:1.21.4-66-d00344a]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1723) ~[paper-1.21.4.jar:1.21.4-66-d00344a]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1529) ~[paper-1.21.4.jar:1.21.4-66-d00344a]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1251) ~[paper-1.21.4.jar:1.21.4-66-d00344a]
	at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:310) ~[paper-1.21.4.jar:1.21.4-66-d00344a]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[12:05:11 ERROR]: Could not pass event PlaceBlockEvent to WorldGuard v7.0.12+829a4a4
java.lang.NoClassDefFoundError: Could not initialize class com.sk89q.worldguard.bukkit.util.Materials
	at worldguard-bukkit-7.0.12-dist.jar/com.sk89q.worldguard.bukkit.listener.RegionProtectionListener.onPlaceBlock(RegionProtectionListener.java:165) ~[worldguard-bukkit-7.0.12-dist.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.4.jar:1.21.4-66-d00344a]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.4.jar:1.21.4-66-d00344a]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
	at worldguard-bukkit-7.0.12-dist.jar/com.sk89q.worldguard.bukkit.util.Events.fireBulkEventToCancel(Events.java:112) ~[worldguard-bukkit-7.0.12-dist.jar:?]
	at worldguard-bukkit-7.0.12-dist.jar/com.sk89q.worldguard.bukkit.listener.EventAbstractionListener.onStructureGrowEvent(EventAbstractionListener.java:278) ~[worldguard-bukkit-7.0.12-dist.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.4.jar:1.21.4-66-d00344a]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.4.jar:1.21.4-66-d00344a]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.world.level.block.SaplingBlock.advanceTree(SaplingBlock.java:74) ~[paper-1.21.4.jar:1.21.4-66-d00344a]
	at net.minecraft.world.level.block.SaplingBlock.randomTick(SaplingBlock.java:50) ~[paper-1.21.4.jar:1.21.4-66-d00344a]
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.randomTick(BlockBehaviour.java:882) ~[paper-1.21.4.jar:1.21.4-66-d00344a]
	at net.minecraft.server.level.ServerLevel.optimiseRandomTick(ServerLevel.java:907) ~[paper-1.21.4.jar:1.21.4-66-d00344a]
	at net.minecraft.server.level.ServerLevel.tickChunk(ServerLevel.java:967) ~[paper-1.21.4.jar:1.21.4-66-d00344a]
	at net.minecraft.server.level.ServerChunkCache.tickChunks(ServerChunkCache.java:624) ~[paper-1.21.4.jar:1.21.4-66-d00344a]
	at net.minecraft.server.level.ServerChunkCache.tickChunks(ServerChunkCache.java:522) ~[paper-1.21.4.jar:1.21.4-66-d00344a]
	at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:494) ~[paper-1.21.4.jar:1.21.4-66-d00344a]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:776) ~[paper-1.21.4.jar:1.21.4-66-d00344a]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1723) ~[paper-1.21.4.jar:1.21.4-66-d00344a]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1529) ~[paper-1.21.4.jar:1.21.4-66-d00344a]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1251) ~[paper-1.21.4.jar:1.21.4-66-d00344a]
	at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:310) ~[paper-1.21.4.jar:1.21.4-66-d00344a]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoSuchFieldError: Class org.bukkit.Tag does not have member field 'org.bukkit.Tag ITEMS_TRIM_TEMPLATES' [in thread "Server thread"]
	at worldguard-bukkit-7.0.12-dist.jar/com.sk89q.worldguard.bukkit.util.Materials.<clinit>(Materials.java:913) ~[worldguard-bukkit-7.0.12-dist.jar:?]
	at worldguard-bukkit-7.0.12-dist.jar/com.sk89q.worldguard.bukkit.listener.RegionFlagsListener.onPlaceBlock(RegionFlagsListener.java:67) ~[worldguard-bukkit-7.0.12-dist.jar:?]
	... 26 more
[12:05:32 ERROR]: Could not pass event PlaceBlockEvent to WorldGuard v7.0.12+829a4a4
java.lang.NoClassDefFoundError: Could not initialize class com.sk89q.worldguard.bukkit.util.Materials
	at worldguard-bukkit-7.0.12-dist.jar/com.sk89q.worldguard.bukkit.listener.RegionFlagsListener.onPlaceBlock(RegionFlagsListener.java:67) ~[worldguard-bukkit-7.0.12-dist.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.4.jar:1.21.4-66-d00344a]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.4.jar:1.21.4-66-d00344a]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
	at worldguard-bukkit-7.0.12-dist.jar/com.sk89q.worldguard.bukkit.util.Events.fireBulkEventToCancel(Events.java:112) ~[worldguard-bukkit-7.0.12-dist.jar:?]
	at worldguard-bukkit-7.0.12-dist.jar/com.sk89q.worldguard.bukkit.listener.EventAbstractionListener.onStructureGrowEvent(EventAbstractionListener.java:278) ~[worldguard-bukkit-7.0.12-dist.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.4.jar:1.21.4-66-d00344a]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.4.jar:1.21.4-66-d00344a]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.world.level.block.SaplingBlock.advanceTree(SaplingBlock.java:74) ~[paper-1.21.4.jar:1.21.4-66-d00344a]
	at net.minecraft.world.level.block.SaplingBlock.randomTick(SaplingBlock.java:50) ~[paper-1.21.4.jar:1.21.4-66-d00344a]
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.randomTick(BlockBehaviour.java:882) ~[paper-1.21.4.jar:1.21.4-66-d00344a]
	at net.minecraft.server.level.ServerLevel.optimiseRandomTick(ServerLevel.java:907) ~[paper-1.21.4.jar:1.21.4-66-d00344a]
	at net.minecraft.server.level.ServerLevel.tickChunk(ServerLevel.java:967) ~[paper-1.21.4.jar:1.21.4-66-d00344a]
	at net.minecraft.server.level.ServerChunkCache.tickChunks(ServerChunkCache.java:624) ~[paper-1.21.4.jar:1.21.4-66-d00344a]
	at net.minecraft.server.level.ServerChunkCache.tickChunks(ServerChunkCache.java:522) ~[paper-1.21.4.jar:1.21.4-66-d00344a]
	at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:494) ~[paper-1.21.4.jar:1.21.4-66-d00344a]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:776) ~[paper-1.21.4.jar:1.21.4-66-d00344a]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1723) ~[paper-1.21.4.jar:1.21.4-66-d00344a]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1529) ~[paper-1.21.4.jar:1.21.4-66-d00344a]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1251) ~[paper-1.21.4.jar:1.21.4-66-d00344a]
	at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:310) ~[paper-1.21.4.jar:1.21.4-66-d00344a]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoSuchFieldError: Class org.bukkit.Tag does not have member field 'org.bukkit.Tag ITEMS_TRIM_TEMPLATES' [in thread "Server thread"]
	at worldguard-bukkit-7.0.12-dist.jar/com.sk89q.worldguard.bukkit.util.Materials.<clinit>(Materials.java:913) ~[worldguard-bukkit-7.0.12-dist.jar:?]
	... 27 more
[12:05:32 ERROR]: Could not pass event PlaceBlockEvent to WorldGuard v7.0.12+829a4a4
java.lang.NoClassDefFoundError: Could not initialize class com.sk89q.worldguard.bukkit.util.Materials
	at worldguard-bukkit-7.0.12-dist.jar/com.sk89q.worldguard.bukkit.listener.RegionProtectionListener.onPlaceBlock(RegionProtectionListener.java:165) ~[worldguard-bukkit-7.0.12-dist.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.4.jar:1.21.4-66-d00344a]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.4.jar:1.21.4-66-d00344a]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
	at worldguard-bukkit-7.0.12-dist.jar/com.sk89q.worldguard.bukkit.util.Events.fireBulkEventToCancel(Events.java:112) ~[worldguard-bukkit-7.0.12-dist.jar:?]
	at worldguard-bukkit-7.0.12-dist.jar/com.sk89q.worldguard.bukkit.listener.EventAbstractionListener.onStructureGrowEvent(EventAbstractionListener.java:278) ~[worldguard-bukkit-7.0.12-dist.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.4.jar:1.21.4-66-d00344a]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.4.jar:1.21.4-66-d00344a]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.world.level.block.SaplingBlock.advanceTree(SaplingBlock.java:74) ~[paper-1.21.4.jar:1.21.4-66-d00344a]
	at net.minecraft.world.level.block.SaplingBlock.randomTick(SaplingBlock.java:50) ~[paper-1.21.4.jar:1.21.4-66-d00344a]
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.randomTick(BlockBehaviour.java:882) ~[paper-1.21.4.jar:1.21.4-66-d00344a]
	at net.minecraft.server.level.ServerLevel.optimiseRandomTick(ServerLevel.java:907) ~[paper-1.21.4.jar:1.21.4-66-d00344a]
	at net.minecraft.server.level.ServerLevel.tickChunk(ServerLevel.java:967) ~[paper-1.21.4.jar:1.21.4-66-d00344a]
	at net.minecraft.server.level.ServerChunkCache.tickChunks(ServerChunkCache.java:624) ~[paper-1.21.4.jar:1.21.4-66-d00344a]
	at net.minecraft.server.level.ServerChunkCache.tickChunks(ServerChunkCache.java:522) ~[paper-1.21.4.jar:1.21.4-66-d00344a]
	at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:494) ~[paper-1.21.4.jar:1.21.4-66-d00344a]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:776) ~[paper-1.21.4.jar:1.21.4-66-d00344a]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1723) ~[paper-1.21.4.jar:1.21.4-66-d00344a]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1529) ~[paper-1.21.4.jar:1.21.4-66-d00344a]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1251) ~[paper-1.21.4.jar:1.21.4-66-d00344a]
	at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:310) ~[paper-1.21.4.jar:1.21.4-66-d00344a]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoSuchFieldError: Class org.bukkit.Tag does not have member field 'org.bukkit.Tag ITEMS_TRIM_TEMPLATES' [in thread "Server thread"]
	at worldguard-bukkit-7.0.12-dist.jar/com.sk89q.worldguard.bukkit.util.Materials.<clinit>(Materials.java:913) ~[worldguard-bukkit-7.0.12-dist.jar:?]
	at worldguard-bukkit-7.0.12-dist.jar/com.sk89q.worldguard.bukkit.listener.RegionFlagsListener.onPlaceBlock(RegionFlagsListener.java:67) ~[worldguard-bukkit-7.0.12-dist.jar:?]
	... 26 more

### Expected Behavior

No errors should show up

### Reproduction Steps

1. Start a server with both WE and WG
2. Make any right click
3. Observe console output

### Optional WorldGuard-Report

https://paste.enginehub.org/pVQshe4sy.report

**Comment by me4502** [comment]
use a version of WorldGuard labelled to support your MC version.

**Comment by Stoupy51** [comment]
It do is labelled to support my MC version:
![Image](https://github.com/user-attachments/assets/52eaef0e-c4f1-429a-ad21-74c4afcf6199)

**Comment by me4502** [comment]
that is not what you said (nor what your logs said) you are using

**Comment by Stoupy51** [comment]
Oh sorry, looks like it downloaded the wrong version on my computer without me noticing it
